/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as github_com_foomo_gotsrpc_v2_tests_common from './vo.common'; // ./client/vo.common.ts to ./client/vo.common.ts

// github.com/foomo/gotsrpc/v2/tests/common.Nested
export interface Nested {
	name:string;
	child:github_com_foomo_gotsrpc_v2_tests_common.Simple;
}
// github.com/foomo/gotsrpc/v2/tests/common.Simple
export interface Simple {
	bool:boolean;
	int:number;
	int64:number;
	float64:number;
	string:string;
}
// end of common js