// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package service

import (
	tls "crypto/tls"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	gorpcconv "github.com/foomo/gotsrpc/v3/semconv/gorpcconv"
	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
	instr  *gorpcconv.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config, opts ...gotsrpc.Option) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{
		instr: gorpcconv.NewClient(append([]gotsrpc.Option{gotsrpc.WithClientService("github.com/foomo/gotsrpc/v3/example/monitor/service", "Service")}, opts...)...),
	}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) Hello(v string) (retHello_0 string, clientErr error) {
	call := tsc.instr.Start("Hello")
	defer call.End()
	rpcReq := ServiceHelloRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceHelloResponse)
	return rpcResp.RetHello_0, nil
}
