// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package service

import (
	"io"
	http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	httpconv "github.com/foomo/gotsrpc/v3/semconv/httpconv"
)

const (
	ServiceGoTSRPCProxyHello = "Hello"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  Service
	instr    *httpconv.Server
}

func NewDefaultServiceGoTSRPCProxy(service Service, opts ...gotsrpc.Option) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/service", opts...)
}

func NewServiceGoTSRPCProxy(service Service, endpoint string, opts ...gotsrpc.Option) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
		instr:    httpconv.NewServer("github.com/foomo/gotsrpc/v3/example/monitor/service", "Service", opts...),
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	r, call := p.instr.Start(w, r, funcName)
	defer call.End()
	switch funcName {
	case ServiceGoTSRPCProxyHello:
		var rets []any
		var (
			arg_v string
		)
		args := []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		helloRet := p.service.Hello(arg_v)
		call.ExecutionEnd()
		rets = []any{helloRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	default:
		call.NotFound()
		gotsrpc.ErrorFuncNotFound(w)
	}
}
