// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package service

import (
	go_context "context"
	go_net_http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	pkg_errors "github.com/pkg/errors"
)

type ServiceGoTSRPCClient interface {
	Hello(ctx go_context.Context, v string) (retHello_0 string, clientErr error)
}

type HTTPServiceGoTSRPCClient struct {
	URL      string
	EndPoint string
	Client   gotsrpc.Client
}

func NewDefaultServiceGoTSRPCClient(url string, opts ...gotsrpc.Option) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClient(url, "/service", opts...)
}

func NewServiceGoTSRPCClient(url string, endpoint string, opts ...gotsrpc.Option) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClientWithClient(url, endpoint, nil, opts...)
}

func NewServiceGoTSRPCClientWithClient(url string, endpoint string, client *go_net_http.Client, opts ...gotsrpc.Option) *HTTPServiceGoTSRPCClient {
	return &HTTPServiceGoTSRPCClient{
		URL:      url,
		EndPoint: endpoint,
		Client:   gotsrpc.NewClientWithHttpClient(client, append([]gotsrpc.Option{gotsrpc.WithClientService("github.com/foomo/gotsrpc/v3/example/monitor/service", "Monitor")}, opts...)...),
	}
}

func (tsc *HTTPServiceGoTSRPCClient) Hello(ctx go_context.Context, v string) (retHello_0 string, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retHello_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "Hello", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call service.ServiceGoTSRPCProxy Hello")
	}
	return
}
