// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	tls "crypto/tls"

	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) Bool(v bool) (retBool_0 bool, clientErr error) {
	rpcReq := ServiceBoolRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolResponse)
	return rpcResp.RetBool_0, nil
}

func (tsc *ServiceGoRPCClient) BoolPtr(v *bool) (retBoolPtr_0 *bool, clientErr error) {
	rpcReq := ServiceBoolPtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolPtrResponse)
	return rpcResp.RetBoolPtr_0, nil
}

func (tsc *ServiceGoRPCClient) ByteSlice(v []byte) (retByteSlice_0 []byte, clientErr error) {
	rpcReq := ServiceByteSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceByteSliceResponse)
	return rpcResp.RetByteSlice_0, nil
}

func (tsc *ServiceGoRPCClient) Empty() (retEmpty_0 bool, clientErr error) {
	rpcReq := ServiceEmptyRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceEmptyResponse)
	return rpcResp.RetEmpty_0, nil
}

func (tsc *ServiceGoRPCClient) Float64(v float64) (retFloat64_0 float64, clientErr error) {
	rpcReq := ServiceFloat64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64Response)
	return rpcResp.RetFloat64_0, nil
}

func (tsc *ServiceGoRPCClient) Int(v int) (retInt_0 int, clientErr error) {
	rpcReq := ServiceIntRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntResponse)
	return rpcResp.RetInt_0, nil
}

func (tsc *ServiceGoRPCClient) Int64(v int64) (retInt64_0 int64, clientErr error) {
	rpcReq := ServiceInt64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64Response)
	return rpcResp.RetInt64_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Ptr(v *int64) (retInt64Ptr_0 *int64, clientErr error) {
	rpcReq := ServiceInt64PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64PtrResponse)
	return rpcResp.RetInt64Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Slice(v []int64) (retInt64Slice_0 []int64, clientErr error) {
	rpcReq := ServiceInt64SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64SliceResponse)
	return rpcResp.RetInt64Slice_0, nil
}

func (tsc *ServiceGoRPCClient) MapOfMaps(v map[string]map[string]string) (retMapOfMaps_0 map[string]map[string]string, clientErr error) {
	rpcReq := ServiceMapOfMapsRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMapOfMapsResponse)
	return rpcResp.RetMapOfMaps_0, nil
}

func (tsc *ServiceGoRPCClient) MapOfSimpleSlice(v map[string][]Simple) (retMapOfSimpleSlice_0 map[string][]Simple, clientErr error) {
	rpcReq := ServiceMapOfSimpleSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMapOfSimpleSliceResponse)
	return rpcResp.RetMapOfSimpleSlice_0, nil
}

func (tsc *ServiceGoRPCClient) MixedArgs(s Simple, items []string, m map[string]int64) (retMixedArgs_0 Simple, retMixedArgs_1 []string, retMixedArgs_2 map[string]int64, clientErr error) {
	rpcReq := ServiceMixedArgsRequest{S: s, Items: items, M: m}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMixedArgsResponse)
	return rpcResp.RetMixedArgs_0, rpcResp.RetMixedArgs_1, rpcResp.RetMixedArgs_2, nil
}

func (tsc *ServiceGoRPCClient) MultiArgs(a string, b int64, c bool) (retMultiArgs_0 string, retMultiArgs_1 int64, retMultiArgs_2 bool, clientErr error) {
	rpcReq := ServiceMultiArgsRequest{A: a, B: b, C: c}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMultiArgsResponse)
	return rpcResp.RetMultiArgs_0, rpcResp.RetMultiArgs_1, rpcResp.RetMultiArgs_2, nil
}

func (tsc *ServiceGoRPCClient) NestedStruct(v Nested) (retNestedStruct_0 Nested, clientErr error) {
	rpcReq := ServiceNestedStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceNestedStructResponse)
	return rpcResp.RetNestedStruct_0, nil
}

func (tsc *ServiceGoRPCClient) ObjectID(v ObjectID) (retObjectID_0 ObjectID, clientErr error) {
	rpcReq := ServiceObjectIDRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceObjectIDResponse)
	return rpcResp.RetObjectID_0, nil
}

func (tsc *ServiceGoRPCClient) SimplePtrSlice(v []*Simple) (retSimplePtrSlice_0 []*Simple, clientErr error) {
	rpcReq := ServiceSimplePtrSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSimplePtrSliceResponse)
	return rpcResp.RetSimplePtrSlice_0, nil
}

func (tsc *ServiceGoRPCClient) SimpleSlice(v []Simple) (retSimpleSlice_0 []Simple, clientErr error) {
	rpcReq := ServiceSimpleSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSimpleSliceResponse)
	return rpcResp.RetSimpleSlice_0, nil
}

func (tsc *ServiceGoRPCClient) SimpleStruct(v Simple) (retSimpleStruct_0 Simple, clientErr error) {
	rpcReq := ServiceSimpleStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSimpleStructResponse)
	return rpcResp.RetSimpleStruct_0, nil
}

func (tsc *ServiceGoRPCClient) SliceOfMaps(v []map[string]string) (retSliceOfMaps_0 []map[string]string, clientErr error) {
	rpcReq := ServiceSliceOfMapsRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSliceOfMapsResponse)
	return rpcResp.RetSliceOfMaps_0, nil
}

func (tsc *ServiceGoRPCClient) String(v string) (retString_0 string, clientErr error) {
	rpcReq := ServiceStringRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringResponse)
	return rpcResp.RetString_0, nil
}

func (tsc *ServiceGoRPCClient) StringInt64Map(v map[string]int64) (retStringInt64Map_0 map[string]int64, clientErr error) {
	rpcReq := ServiceStringInt64MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringInt64MapResponse)
	return rpcResp.RetStringInt64Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringPtr(v *string) (retStringPtr_0 *string, clientErr error) {
	rpcReq := ServiceStringPtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringPtrResponse)
	return rpcResp.RetStringPtr_0, nil
}

func (tsc *ServiceGoRPCClient) StringSimpleMap(v map[string]Simple) (retStringSimpleMap_0 map[string]Simple, clientErr error) {
	rpcReq := ServiceStringSimpleMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSimpleMapResponse)
	return rpcResp.RetStringSimpleMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringSimplePtrMap(v map[string]*Simple) (retStringSimplePtrMap_0 map[string]*Simple, clientErr error) {
	rpcReq := ServiceStringSimplePtrMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSimplePtrMapResponse)
	return rpcResp.RetStringSimplePtrMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringSlice(v []string) (retStringSlice_0 []string, clientErr error) {
	rpcReq := ServiceStringSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSliceResponse)
	return rpcResp.RetStringSlice_0, nil
}

func (tsc *ServiceGoRPCClient) StringSlice2D(v [][]string) (retStringSlice2D_0 [][]string, clientErr error) {
	rpcReq := ServiceStringSlice2DRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSlice2DResponse)
	return rpcResp.RetStringSlice2D_0, nil
}

func (tsc *ServiceGoRPCClient) StringStringMap(v map[string]string) (retStringStringMap_0 map[string]string, clientErr error) {
	rpcReq := ServiceStringStringMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringStringMapResponse)
	return rpcResp.RetStringStringMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringStringSliceMap(v map[string][]string) (retStringStringSliceMap_0 map[string][]string, clientErr error) {
	rpcReq := ServiceStringStringSliceMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringStringSliceMapResponse)
	return rpcResp.RetStringStringSliceMap_0, nil
}

func (tsc *ServiceGoRPCClient) StructWithCollections(v WithCollections) (retStructWithCollections_0 WithCollections, clientErr error) {
	rpcReq := ServiceStructWithCollectionsRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStructWithCollectionsResponse)
	return rpcResp.RetStructWithCollections_0, nil
}

func (tsc *ServiceGoRPCClient) StructWithPointers(v WithPointers) (retStructWithPointers_0 WithPointers, clientErr error) {
	rpcReq := ServiceStructWithPointersRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStructWithPointersResponse)
	return rpcResp.RetStructWithPointers_0, nil
}
