// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package server

import (
	tls "crypto/tls"
	encoding_json "encoding/json"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	gorpcconv "github.com/foomo/gotsrpc/v3/semconv/gorpcconv"
	github_com_foomo_gotsrpc_v3_tests_common "github.com/foomo/gotsrpc/v3/tests/common"
	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
	instr  *gorpcconv.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config, opts ...gotsrpc.Option) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{
		instr: gorpcconv.NewClient(append([]gotsrpc.Option{gotsrpc.WithClientService("github.com/foomo/gotsrpc/v3/tests/types/server", "Service")}, opts...)...),
	}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) AllScalarMapsStruct(v AllScalarMaps) (retAllScalarMapsStruct_0 AllScalarMaps, clientErr error) {
	call := tsc.instr.Start("AllScalarMapsStruct")
	defer call.End()
	rpcReq := ServiceAllScalarMapsStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceAllScalarMapsStructResponse)
	return rpcResp.RetAllScalarMapsStruct_0, nil
}

func (tsc *ServiceGoRPCClient) AllScalarPointersStruct(v AllScalarPointers) (retAllScalarPointersStruct_0 AllScalarPointers, clientErr error) {
	call := tsc.instr.Start("AllScalarPointersStruct")
	defer call.End()
	rpcReq := ServiceAllScalarPointersStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceAllScalarPointersStructResponse)
	return rpcResp.RetAllScalarPointersStruct_0, nil
}

func (tsc *ServiceGoRPCClient) AllScalarSlicesStruct(v AllScalarSlices) (retAllScalarSlicesStruct_0 AllScalarSlices, clientErr error) {
	call := tsc.instr.Start("AllScalarSlicesStruct")
	defer call.End()
	rpcReq := ServiceAllScalarSlicesStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceAllScalarSlicesStructResponse)
	return rpcResp.RetAllScalarSlicesStruct_0, nil
}

func (tsc *ServiceGoRPCClient) AllScalarsStruct(v AllScalars) (retAllScalarsStruct_0 AllScalars, clientErr error) {
	call := tsc.instr.Start("AllScalarsStruct")
	defer call.End()
	rpcReq := ServiceAllScalarsStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceAllScalarsStructResponse)
	return rpcResp.RetAllScalarsStruct_0, nil
}

func (tsc *ServiceGoRPCClient) Bool(v bool) (retBool_0 bool, clientErr error) {
	call := tsc.instr.Start("Bool")
	defer call.End()
	rpcReq := ServiceBoolRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolResponse)
	return rpcResp.RetBool_0, nil
}

func (tsc *ServiceGoRPCClient) BoolPtr(v *bool) (retBoolPtr_0 *bool, clientErr error) {
	call := tsc.instr.Start("BoolPtr")
	defer call.End()
	rpcReq := ServiceBoolPtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolPtrResponse)
	return rpcResp.RetBoolPtr_0, nil
}

func (tsc *ServiceGoRPCClient) ByteSlice(v []byte) (retByteSlice_0 []byte, clientErr error) {
	call := tsc.instr.Start("ByteSlice")
	defer call.End()
	rpcReq := ServiceByteSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceByteSliceResponse)
	return rpcResp.RetByteSlice_0, nil
}

func (tsc *ServiceGoRPCClient) Empty() (retEmpty_0 bool, clientErr error) {
	call := tsc.instr.Start("Empty")
	defer call.End()
	rpcReq := ServiceEmptyRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceEmptyResponse)
	return rpcResp.RetEmpty_0, nil
}

func (tsc *ServiceGoRPCClient) Float32(v float32) (retFloat32_0 float32, clientErr error) {
	call := tsc.instr.Start("Float32")
	defer call.End()
	rpcReq := ServiceFloat32Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32Response)
	return rpcResp.RetFloat32_0, nil
}

func (tsc *ServiceGoRPCClient) Float32Ptr(v *float32) (retFloat32Ptr_0 *float32, clientErr error) {
	call := tsc.instr.Start("Float32Ptr")
	defer call.End()
	rpcReq := ServiceFloat32PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32PtrResponse)
	return rpcResp.RetFloat32Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Float32Slice(v []float32) (retFloat32Slice_0 []float32, clientErr error) {
	call := tsc.instr.Start("Float32Slice")
	defer call.End()
	rpcReq := ServiceFloat32SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32SliceResponse)
	return rpcResp.RetFloat32Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Float64(v float64) (retFloat64_0 float64, clientErr error) {
	call := tsc.instr.Start("Float64")
	defer call.End()
	rpcReq := ServiceFloat64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64Response)
	return rpcResp.RetFloat64_0, nil
}

func (tsc *ServiceGoRPCClient) InlinedMixedStruct(v InlinedMixed) (retInlinedMixedStruct_0 InlinedMixed, clientErr error) {
	call := tsc.instr.Start("InlinedMixedStruct")
	defer call.End()
	rpcReq := ServiceInlinedMixedStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInlinedMixedStructResponse)
	return rpcResp.RetInlinedMixedStruct_0, nil
}

func (tsc *ServiceGoRPCClient) InlinedMultipleStruct(v InlinedMultiple) (retInlinedMultipleStruct_0 InlinedMultiple, clientErr error) {
	call := tsc.instr.Start("InlinedMultipleStruct")
	defer call.End()
	rpcReq := ServiceInlinedMultipleStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInlinedMultipleStructResponse)
	return rpcResp.RetInlinedMultipleStruct_0, nil
}

func (tsc *ServiceGoRPCClient) InlinedPtrStruct(v InlinedPtr) (retInlinedPtrStruct_0 InlinedPtr, clientErr error) {
	call := tsc.instr.Start("InlinedPtrStruct")
	defer call.End()
	rpcReq := ServiceInlinedPtrStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInlinedPtrStructResponse)
	return rpcResp.RetInlinedPtrStruct_0, nil
}

func (tsc *ServiceGoRPCClient) InlinedStruct(v Inlined) (retInlinedStruct_0 Inlined, clientErr error) {
	call := tsc.instr.Start("InlinedStruct")
	defer call.End()
	rpcReq := ServiceInlinedStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInlinedStructResponse)
	return rpcResp.RetInlinedStruct_0, nil
}

func (tsc *ServiceGoRPCClient) Int(v int) (retInt_0 int, clientErr error) {
	call := tsc.instr.Start("Int")
	defer call.End()
	rpcReq := ServiceIntRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntResponse)
	return rpcResp.RetInt_0, nil
}

func (tsc *ServiceGoRPCClient) Int16(v int16) (retInt16_0 int16, clientErr error) {
	call := tsc.instr.Start("Int16")
	defer call.End()
	rpcReq := ServiceInt16Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt16Response)
	return rpcResp.RetInt16_0, nil
}

func (tsc *ServiceGoRPCClient) Int16Ptr(v *int16) (retInt16Ptr_0 *int16, clientErr error) {
	call := tsc.instr.Start("Int16Ptr")
	defer call.End()
	rpcReq := ServiceInt16PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt16PtrResponse)
	return rpcResp.RetInt16Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Int16Slice(v []int16) (retInt16Slice_0 []int16, clientErr error) {
	call := tsc.instr.Start("Int16Slice")
	defer call.End()
	rpcReq := ServiceInt16SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt16SliceResponse)
	return rpcResp.RetInt16Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Int32(v int32) (retInt32_0 int32, clientErr error) {
	call := tsc.instr.Start("Int32")
	defer call.End()
	rpcReq := ServiceInt32Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32Response)
	return rpcResp.RetInt32_0, nil
}

func (tsc *ServiceGoRPCClient) Int32Ptr(v *int32) (retInt32Ptr_0 *int32, clientErr error) {
	call := tsc.instr.Start("Int32Ptr")
	defer call.End()
	rpcReq := ServiceInt32PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32PtrResponse)
	return rpcResp.RetInt32Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Int32Slice(v []int32) (retInt32Slice_0 []int32, clientErr error) {
	call := tsc.instr.Start("Int32Slice")
	defer call.End()
	rpcReq := ServiceInt32SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32SliceResponse)
	return rpcResp.RetInt32Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Int64(v int64) (retInt64_0 int64, clientErr error) {
	call := tsc.instr.Start("Int64")
	defer call.End()
	rpcReq := ServiceInt64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64Response)
	return rpcResp.RetInt64_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Ptr(v *int64) (retInt64Ptr_0 *int64, clientErr error) {
	call := tsc.instr.Start("Int64Ptr")
	defer call.End()
	rpcReq := ServiceInt64PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64PtrResponse)
	return rpcResp.RetInt64Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Slice(v []int64) (retInt64Slice_0 []int64, clientErr error) {
	call := tsc.instr.Start("Int64Slice")
	defer call.End()
	rpcReq := ServiceInt64SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64SliceResponse)
	return rpcResp.RetInt64Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Int8(v int8) (retInt8_0 int8, clientErr error) {
	call := tsc.instr.Start("Int8")
	defer call.End()
	rpcReq := ServiceInt8Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt8Response)
	return rpcResp.RetInt8_0, nil
}

func (tsc *ServiceGoRPCClient) Int8Ptr(v *int8) (retInt8Ptr_0 *int8, clientErr error) {
	call := tsc.instr.Start("Int8Ptr")
	defer call.End()
	rpcReq := ServiceInt8PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt8PtrResponse)
	return rpcResp.RetInt8Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Int8Slice(v []int8) (retInt8Slice_0 []int8, clientErr error) {
	call := tsc.instr.Start("Int8Slice")
	defer call.End()
	rpcReq := ServiceInt8SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt8SliceResponse)
	return rpcResp.RetInt8Slice_0, nil
}

func (tsc *ServiceGoRPCClient) JSONRawMessage(v encoding_json.RawMessage) (retJSONRawMessage_0 encoding_json.RawMessage, clientErr error) {
	call := tsc.instr.Start("JSONRawMessage")
	defer call.End()
	rpcReq := ServiceJSONRawMessageRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceJSONRawMessageResponse)
	return rpcResp.RetJSONRawMessage_0, nil
}

func (tsc *ServiceGoRPCClient) MapOfMaps(v map[string]map[string]string) (retMapOfMaps_0 map[string]map[string]string, clientErr error) {
	call := tsc.instr.Start("MapOfMaps")
	defer call.End()
	rpcReq := ServiceMapOfMapsRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMapOfMapsResponse)
	return rpcResp.RetMapOfMaps_0, nil
}

func (tsc *ServiceGoRPCClient) MapOfSimpleSlice(v map[string][]github_com_foomo_gotsrpc_v3_tests_common.Simple) (retMapOfSimpleSlice_0 map[string][]github_com_foomo_gotsrpc_v3_tests_common.Simple, clientErr error) {
	call := tsc.instr.Start("MapOfSimpleSlice")
	defer call.End()
	rpcReq := ServiceMapOfSimpleSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMapOfSimpleSliceResponse)
	return rpcResp.RetMapOfSimpleSlice_0, nil
}

func (tsc *ServiceGoRPCClient) MixedArgs(s github_com_foomo_gotsrpc_v3_tests_common.Simple, items []string, m map[string]int64) (retMixedArgs_0 github_com_foomo_gotsrpc_v3_tests_common.Simple, retMixedArgs_1 []string, retMixedArgs_2 map[string]int64, clientErr error) {
	call := tsc.instr.Start("MixedArgs")
	defer call.End()
	rpcReq := ServiceMixedArgsRequest{S: s, Items: items, M: m}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMixedArgsResponse)
	return rpcResp.RetMixedArgs_0, rpcResp.RetMixedArgs_1, rpcResp.RetMixedArgs_2, nil
}

func (tsc *ServiceGoRPCClient) MultiArgs(a string, b int64, c bool) (retMultiArgs_0 string, retMultiArgs_1 int64, retMultiArgs_2 bool, clientErr error) {
	call := tsc.instr.Start("MultiArgs")
	defer call.End()
	rpcReq := ServiceMultiArgsRequest{A: a, B: b, C: c}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceMultiArgsResponse)
	return rpcResp.RetMultiArgs_0, rpcResp.RetMultiArgs_1, rpcResp.RetMultiArgs_2, nil
}

func (tsc *ServiceGoRPCClient) NestedStruct(v github_com_foomo_gotsrpc_v3_tests_common.Nested) (retNestedStruct_0 github_com_foomo_gotsrpc_v3_tests_common.Nested, clientErr error) {
	call := tsc.instr.Start("NestedStruct")
	defer call.End()
	rpcReq := ServiceNestedStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceNestedStructResponse)
	return rpcResp.RetNestedStruct_0, nil
}

func (tsc *ServiceGoRPCClient) ObjectID(v ObjectID) (retObjectID_0 ObjectID, clientErr error) {
	call := tsc.instr.Start("ObjectID")
	defer call.End()
	rpcReq := ServiceObjectIDRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceObjectIDResponse)
	return rpcResp.RetObjectID_0, nil
}

func (tsc *ServiceGoRPCClient) SimplePtrSlice(v []*github_com_foomo_gotsrpc_v3_tests_common.Simple) (retSimplePtrSlice_0 []*github_com_foomo_gotsrpc_v3_tests_common.Simple, clientErr error) {
	call := tsc.instr.Start("SimplePtrSlice")
	defer call.End()
	rpcReq := ServiceSimplePtrSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSimplePtrSliceResponse)
	return rpcResp.RetSimplePtrSlice_0, nil
}

func (tsc *ServiceGoRPCClient) SimpleSlice(v []github_com_foomo_gotsrpc_v3_tests_common.Simple) (retSimpleSlice_0 []github_com_foomo_gotsrpc_v3_tests_common.Simple, clientErr error) {
	call := tsc.instr.Start("SimpleSlice")
	defer call.End()
	rpcReq := ServiceSimpleSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSimpleSliceResponse)
	return rpcResp.RetSimpleSlice_0, nil
}

func (tsc *ServiceGoRPCClient) SimpleStruct(v github_com_foomo_gotsrpc_v3_tests_common.Simple) (retSimpleStruct_0 github_com_foomo_gotsrpc_v3_tests_common.Simple, clientErr error) {
	call := tsc.instr.Start("SimpleStruct")
	defer call.End()
	rpcReq := ServiceSimpleStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSimpleStructResponse)
	return rpcResp.RetSimpleStruct_0, nil
}

func (tsc *ServiceGoRPCClient) SliceOfMaps(v []map[string]string) (retSliceOfMaps_0 []map[string]string, clientErr error) {
	call := tsc.instr.Start("SliceOfMaps")
	defer call.End()
	rpcReq := ServiceSliceOfMapsRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceSliceOfMapsResponse)
	return rpcResp.RetSliceOfMaps_0, nil
}

func (tsc *ServiceGoRPCClient) String(v string) (retString_0 string, clientErr error) {
	call := tsc.instr.Start("String")
	defer call.End()
	rpcReq := ServiceStringRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringResponse)
	return rpcResp.RetString_0, nil
}

func (tsc *ServiceGoRPCClient) StringFloat32Map(v map[string]float32) (retStringFloat32Map_0 map[string]float32, clientErr error) {
	call := tsc.instr.Start("StringFloat32Map")
	defer call.End()
	rpcReq := ServiceStringFloat32MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringFloat32MapResponse)
	return rpcResp.RetStringFloat32Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringInt16Map(v map[string]int16) (retStringInt16Map_0 map[string]int16, clientErr error) {
	call := tsc.instr.Start("StringInt16Map")
	defer call.End()
	rpcReq := ServiceStringInt16MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringInt16MapResponse)
	return rpcResp.RetStringInt16Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringInt32Map(v map[string]int32) (retStringInt32Map_0 map[string]int32, clientErr error) {
	call := tsc.instr.Start("StringInt32Map")
	defer call.End()
	rpcReq := ServiceStringInt32MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringInt32MapResponse)
	return rpcResp.RetStringInt32Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringInt64Map(v map[string]int64) (retStringInt64Map_0 map[string]int64, clientErr error) {
	call := tsc.instr.Start("StringInt64Map")
	defer call.End()
	rpcReq := ServiceStringInt64MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringInt64MapResponse)
	return rpcResp.RetStringInt64Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringInt8Map(v map[string]int8) (retStringInt8Map_0 map[string]int8, clientErr error) {
	call := tsc.instr.Start("StringInt8Map")
	defer call.End()
	rpcReq := ServiceStringInt8MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringInt8MapResponse)
	return rpcResp.RetStringInt8Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringObjectID(v StringObjectID) (retStringObjectID_0 StringObjectID, clientErr error) {
	call := tsc.instr.Start("StringObjectID")
	defer call.End()
	rpcReq := ServiceStringObjectIDRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringObjectIDResponse)
	return rpcResp.RetStringObjectID_0, nil
}

func (tsc *ServiceGoRPCClient) StringPtr(v *string) (retStringPtr_0 *string, clientErr error) {
	call := tsc.instr.Start("StringPtr")
	defer call.End()
	rpcReq := ServiceStringPtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringPtrResponse)
	return rpcResp.RetStringPtr_0, nil
}

func (tsc *ServiceGoRPCClient) StringSimpleMap(v map[string]github_com_foomo_gotsrpc_v3_tests_common.Simple) (retStringSimpleMap_0 map[string]github_com_foomo_gotsrpc_v3_tests_common.Simple, clientErr error) {
	call := tsc.instr.Start("StringSimpleMap")
	defer call.End()
	rpcReq := ServiceStringSimpleMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSimpleMapResponse)
	return rpcResp.RetStringSimpleMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringSimplePtrMap(v map[string]*github_com_foomo_gotsrpc_v3_tests_common.Simple) (retStringSimplePtrMap_0 map[string]*github_com_foomo_gotsrpc_v3_tests_common.Simple, clientErr error) {
	call := tsc.instr.Start("StringSimplePtrMap")
	defer call.End()
	rpcReq := ServiceStringSimplePtrMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSimplePtrMapResponse)
	return rpcResp.RetStringSimplePtrMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringSlice(v []string) (retStringSlice_0 []string, clientErr error) {
	call := tsc.instr.Start("StringSlice")
	defer call.End()
	rpcReq := ServiceStringSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSliceResponse)
	return rpcResp.RetStringSlice_0, nil
}

func (tsc *ServiceGoRPCClient) StringSlice2D(v [][]string) (retStringSlice2D_0 [][]string, clientErr error) {
	call := tsc.instr.Start("StringSlice2D")
	defer call.End()
	rpcReq := ServiceStringSlice2DRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSlice2DResponse)
	return rpcResp.RetStringSlice2D_0, nil
}

func (tsc *ServiceGoRPCClient) StringStringMap(v map[string]string) (retStringStringMap_0 map[string]string, clientErr error) {
	call := tsc.instr.Start("StringStringMap")
	defer call.End()
	rpcReq := ServiceStringStringMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringStringMapResponse)
	return rpcResp.RetStringStringMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringStringSliceMap(v map[string][]string) (retStringStringSliceMap_0 map[string][]string, clientErr error) {
	call := tsc.instr.Start("StringStringSliceMap")
	defer call.End()
	rpcReq := ServiceStringStringSliceMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringStringSliceMapResponse)
	return rpcResp.RetStringStringSliceMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringUint16Map(v map[string]uint16) (retStringUint16Map_0 map[string]uint16, clientErr error) {
	call := tsc.instr.Start("StringUint16Map")
	defer call.End()
	rpcReq := ServiceStringUint16MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringUint16MapResponse)
	return rpcResp.RetStringUint16Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringUint32Map(v map[string]uint32) (retStringUint32Map_0 map[string]uint32, clientErr error) {
	call := tsc.instr.Start("StringUint32Map")
	defer call.End()
	rpcReq := ServiceStringUint32MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringUint32MapResponse)
	return rpcResp.RetStringUint32Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringUint64Map(v map[string]uint64) (retStringUint64Map_0 map[string]uint64, clientErr error) {
	call := tsc.instr.Start("StringUint64Map")
	defer call.End()
	rpcReq := ServiceStringUint64MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringUint64MapResponse)
	return rpcResp.RetStringUint64Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringUint8Map(v map[string]uint8) (retStringUint8Map_0 map[string]uint8, clientErr error) {
	call := tsc.instr.Start("StringUint8Map")
	defer call.End()
	rpcReq := ServiceStringUint8MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringUint8MapResponse)
	return rpcResp.RetStringUint8Map_0, nil
}

func (tsc *ServiceGoRPCClient) StringUintMap(v map[string]uint) (retStringUintMap_0 map[string]uint, clientErr error) {
	call := tsc.instr.Start("StringUintMap")
	defer call.End()
	rpcReq := ServiceStringUintMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringUintMapResponse)
	return rpcResp.RetStringUintMap_0, nil
}

func (tsc *ServiceGoRPCClient) StructWithCollections(v WithCollections) (retStructWithCollections_0 WithCollections, clientErr error) {
	call := tsc.instr.Start("StructWithCollections")
	defer call.End()
	rpcReq := ServiceStructWithCollectionsRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStructWithCollectionsResponse)
	return rpcResp.RetStructWithCollections_0, nil
}

func (tsc *ServiceGoRPCClient) StructWithPointers(v WithPointers) (retStructWithPointers_0 WithPointers, clientErr error) {
	call := tsc.instr.Start("StructWithPointers")
	defer call.End()
	rpcReq := ServiceStructWithPointersRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStructWithPointersResponse)
	return rpcResp.RetStructWithPointers_0, nil
}

func (tsc *ServiceGoRPCClient) Uint(v uint) (retUint_0 uint, clientErr error) {
	call := tsc.instr.Start("Uint")
	defer call.End()
	rpcReq := ServiceUintRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUintResponse)
	return rpcResp.RetUint_0, nil
}

func (tsc *ServiceGoRPCClient) Uint16(v uint16) (retUint16_0 uint16, clientErr error) {
	call := tsc.instr.Start("Uint16")
	defer call.End()
	rpcReq := ServiceUint16Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint16Response)
	return rpcResp.RetUint16_0, nil
}

func (tsc *ServiceGoRPCClient) Uint16Ptr(v *uint16) (retUint16Ptr_0 *uint16, clientErr error) {
	call := tsc.instr.Start("Uint16Ptr")
	defer call.End()
	rpcReq := ServiceUint16PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint16PtrResponse)
	return rpcResp.RetUint16Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Uint16Slice(v []uint16) (retUint16Slice_0 []uint16, clientErr error) {
	call := tsc.instr.Start("Uint16Slice")
	defer call.End()
	rpcReq := ServiceUint16SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint16SliceResponse)
	return rpcResp.RetUint16Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Uint32(v uint32) (retUint32_0 uint32, clientErr error) {
	call := tsc.instr.Start("Uint32")
	defer call.End()
	rpcReq := ServiceUint32Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint32Response)
	return rpcResp.RetUint32_0, nil
}

func (tsc *ServiceGoRPCClient) Uint32Ptr(v *uint32) (retUint32Ptr_0 *uint32, clientErr error) {
	call := tsc.instr.Start("Uint32Ptr")
	defer call.End()
	rpcReq := ServiceUint32PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint32PtrResponse)
	return rpcResp.RetUint32Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Uint32Slice(v []uint32) (retUint32Slice_0 []uint32, clientErr error) {
	call := tsc.instr.Start("Uint32Slice")
	defer call.End()
	rpcReq := ServiceUint32SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint32SliceResponse)
	return rpcResp.RetUint32Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Uint64(v uint64) (retUint64_0 uint64, clientErr error) {
	call := tsc.instr.Start("Uint64")
	defer call.End()
	rpcReq := ServiceUint64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint64Response)
	return rpcResp.RetUint64_0, nil
}

func (tsc *ServiceGoRPCClient) Uint64Ptr(v *uint64) (retUint64Ptr_0 *uint64, clientErr error) {
	call := tsc.instr.Start("Uint64Ptr")
	defer call.End()
	rpcReq := ServiceUint64PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint64PtrResponse)
	return rpcResp.RetUint64Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) Uint64Slice(v []uint64) (retUint64Slice_0 []uint64, clientErr error) {
	call := tsc.instr.Start("Uint64Slice")
	defer call.End()
	rpcReq := ServiceUint64SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint64SliceResponse)
	return rpcResp.RetUint64Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Uint8(v uint8) (retUint8_0 uint8, clientErr error) {
	call := tsc.instr.Start("Uint8")
	defer call.End()
	rpcReq := ServiceUint8Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint8Response)
	return rpcResp.RetUint8_0, nil
}

func (tsc *ServiceGoRPCClient) Uint8Ptr(v *uint8) (retUint8Ptr_0 *uint8, clientErr error) {
	call := tsc.instr.Start("Uint8Ptr")
	defer call.End()
	rpcReq := ServiceUint8PtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUint8PtrResponse)
	return rpcResp.RetUint8Ptr_0, nil
}

func (tsc *ServiceGoRPCClient) UintPtr(v *uint) (retUintPtr_0 *uint, clientErr error) {
	call := tsc.instr.Start("UintPtr")
	defer call.End()
	rpcReq := ServiceUintPtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUintPtrResponse)
	return rpcResp.RetUintPtr_0, nil
}

func (tsc *ServiceGoRPCClient) UintSlice(v []uint) (retUintSlice_0 []uint, clientErr error) {
	call := tsc.instr.Start("UintSlice")
	defer call.End()
	rpcReq := ServiceUintSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUintSliceResponse)
	return rpcResp.RetUintSlice_0, nil
}
