// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	http "net/http"
	time "time"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	github_com_foomo_gotsrpc_v2_tests_common "github.com/foomo/gotsrpc/v2/tests/common"
)

const (
	ServiceGoTSRPCProxyGetContainer      = "GetContainer"
	ServiceGoTSRPCProxyGetItemResponse   = "GetItemResponse"
	ServiceGoTSRPCProxyGetNestedGeneric  = "GetNestedGeneric"
	ServiceGoTSRPCProxyGetPagedItems     = "GetPagedItems"
	ServiceGoTSRPCProxyGetPair           = "GetPair"
	ServiceGoTSRPCProxyGetResult         = "GetResult"
	ServiceGoTSRPCProxyGetStringResponse = "GetStringResponse"
	ServiceGoTSRPCProxySetItemResponse   = "SetItemResponse"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  Service
}

func NewDefaultServiceGoTSRPCProxy(service Service) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/service")
}

func NewServiceGoTSRPCProxy(service Service, endpoint string) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, _ := gotsrpc.GetStatsForRequest(r)
	if callStats != nil {
		callStats.Func = funcName
		callStats.Package = "github.com/foomo/gotsrpc/v2/tests/generics/server"
		callStats.Service = "Service"
	}
	switch funcName {
	case ServiceGoTSRPCProxyGetContainer:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getContainerRet := p.service.GetContainer(r.Context())
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getContainerRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetItemResponse:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getItemResponseRet := p.service.GetItemResponse(r.Context())
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getItemResponseRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetNestedGeneric:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getNestedGenericRet := p.service.GetNestedGeneric(r.Context())
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getNestedGenericRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetPagedItems:
		var (
			args []any
			rets []any
		)
		var (
			arg_page int
		)
		args = []any{&arg_page}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getPagedItemsRet := p.service.GetPagedItems(r.Context(), arg_page)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getPagedItemsRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetPair:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getPairRet := p.service.GetPair(r.Context())
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getPairRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetResult:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getResultRet := p.service.GetResult(r.Context())
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getResultRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetStringResponse:
		var (
			args []any
			rets []any
		)
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		getStringResponseRet := p.service.GetStringResponse(r.Context())
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{getStringResponseRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxySetItemResponse:
		var (
			args []any
			rets []any
		)
		var (
			arg_req github_com_foomo_gotsrpc_v2_tests_common.Response[github_com_foomo_gotsrpc_v2_tests_common.Item]
		)
		args = []any{&arg_req}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		setItemResponseRet := p.service.SetItemResponse(r.Context(), arg_req)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{setItemResponseRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
