# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  - package-ecosystem: github-actions
    commit-message: { prefix: sec(gha) }
    open-pull-requests-limit: 0
    directory: '/'
    schedule:
      interval: daily
      timezone: Europe/Berlin
    groups:
      security:
        applies-to: security-updates
        group-by: dependency-name
        patterns: ['*']
    cooldown:
      default-days: 3

  - package-ecosystem: gomod
    commit-message: { prefix: sec(gomod) }
    open-pull-requests-limit: 0
    directories: [ '**/*' ]
    schedule:
      interval: daily
      timezone: Europe/Berlin
    groups:
      security:
        applies-to: security-updates
        group-by: dependency-name
        patterns: ['*']
    cooldown:
      default-days: 3

  - package-ecosystem: docker
    commit-message: { prefix: sec(docker) }
    open-pull-requests-limit: 0
    directory: '/'
    schedule:
      interval: daily
      timezone: Europe/Berlin
    groups:
      security:
        applies-to: security-updates
        group-by: dependency-name
        patterns: ['*']
    cooldown:
      default-days: 3
