// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package server

import (
	tls "crypto/tls"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	gorpcconv "github.com/foomo/gotsrpc/v3/semconv/gorpcconv"
	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
	instr  *gorpcconv.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config, opts ...gotsrpc.Option) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{
		instr: gorpcconv.NewClient(append([]gotsrpc.Option{gotsrpc.WithClientService("github.com/foomo/gotsrpc/v3/tests/nullable/server", "Service")}, opts...)...),
	}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) VariantA(i1 Base) (r1 Base, clientErr error) {
	call := tsc.instr.Start("VariantA")
	defer call.End()
	rpcReq := ServiceVariantARequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantAResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantB(i1 BCustomType) (r1 BCustomType, clientErr error) {
	call := tsc.instr.Start("VariantB")
	defer call.End()
	rpcReq := ServiceVariantBRequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantBResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantC(i1 BCustomTypes) (r1 BCustomTypes, clientErr error) {
	call := tsc.instr.Start("VariantC")
	defer call.End()
	rpcReq := ServiceVariantCRequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantCResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantD(i1 BCustomTypesMap) (r1 BCustomTypesMap, clientErr error) {
	call := tsc.instr.Start("VariantD")
	defer call.End()
	rpcReq := ServiceVariantDRequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantDResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantE(i1 *Base) (r1 *Base, clientErr error) {
	call := tsc.instr.Start("VariantE")
	defer call.End()
	rpcReq := ServiceVariantERequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantEResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantF(i1 []*Base) (r1 []*Base, clientErr error) {
	call := tsc.instr.Start("VariantF")
	defer call.End()
	rpcReq := ServiceVariantFRequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantFResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantG(i1 map[string]*Base) (r1 map[string]*Base, clientErr error) {
	call := tsc.instr.Start("VariantG")
	defer call.End()
	rpcReq := ServiceVariantGRequest{I1: i1}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantGResponse)
	return rpcResp.R1, nil
}

func (tsc *ServiceGoRPCClient) VariantH(i1 Base, i2 *Base, i3 []*Base, i4 map[string]Base) (r1 Base, r2 *Base, r3 []*Base, r4 map[string]Base, clientErr error) {
	call := tsc.instr.Start("VariantH")
	defer call.End()
	rpcReq := ServiceVariantHRequest{I1: i1, I2: i2, I3: i3, I4: i4}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceVariantHResponse)
	return rpcResp.R1, rpcResp.R2, rpcResp.R3, rpcResp.R4, nil
}
