// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	io "io"
	http "net/http"
	time "time"

	gotsrpc "github.com/foomo/gotsrpc/v2"
)

const (
	ServiceGoTSRPCProxyVariantA = "VariantA"
	ServiceGoTSRPCProxyVariantB = "VariantB"
	ServiceGoTSRPCProxyVariantC = "VariantC"
	ServiceGoTSRPCProxyVariantD = "VariantD"
	ServiceGoTSRPCProxyVariantE = "VariantE"
	ServiceGoTSRPCProxyVariantF = "VariantF"
	ServiceGoTSRPCProxyVariantG = "VariantG"
	ServiceGoTSRPCProxyVariantH = "VariantH"
)

type ServiceGoTSRPCProxy struct {
	EndPoint    string
	service     Service
	lastIsError map[string]bool
}

func NewDefaultServiceGoTSRPCProxy(service Service) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/service")
}

func NewServiceGoTSRPCProxy(service Service, endpoint string) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
		lastIsError: map[string]bool{
			"VariantA": false,
			"VariantB": false,
			"VariantC": false,
			"VariantD": false,
			"VariantE": false,
			"VariantF": false,
			"VariantG": false,
			"VariantH": false,
		},
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, _ := gotsrpc.GetStatsForRequest(r)
	callStats.Func = funcName
	callStats.Package = "github.com/foomo/gotsrpc/v2/tests/nullable/server"
	callStats.Service = "Service"
	switch funcName {
	case ServiceGoTSRPCProxyVariantA:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 Base
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantAR1 := p.service.VariantA(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantAR1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantB:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 BCustomType
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantBR1 := p.service.VariantB(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantBR1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantC:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 BCustomTypes
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantCR1 := p.service.VariantC(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantCR1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantD:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 BCustomTypesMap
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantDR1 := p.service.VariantD(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantDR1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantE:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 *Base
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantER1 := p.service.VariantE(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantER1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantF:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 []*Base
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantFR1 := p.service.VariantF(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantFR1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantG:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 map[string]*Base
		)
		args = []any{&arg_i1}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantGR1 := p.service.VariantG(r.Context(), arg_i1)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantGR1}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyVariantH:
		var (
			args []any
			rets []any
		)
		var (
			arg_i1 Base
			arg_i2 *Base
			arg_i3 []*Base
			arg_i4 map[string]Base
		)
		args = []any{&arg_i1, &arg_i2, &arg_i3, &arg_i4}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		variantHR1, variantHR2, variantHR3, variantHR4 := p.service.VariantH(r.Context(), arg_i1, arg_i2, arg_i3, arg_i4)
		callStats.Execution = time.Since(executionStart)
		rets = []any{variantHR1, variantHR2, variantHR3, variantHR4}
		if err := gotsrpc.Reply(rets, p.lastIsError[funcName], callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
