#:schema https://mise.jdx.dev/schema/mise.json

[settings]
minimum_release_age = "3d"

[tools]
# https://mise-tools.jdx.dev/tools/bun
bun = "1.4.2"
# https://mise-tools.jdx.dev/tools/golangci-lint
golangci-lint = "2.14.0"
# https://mise-tools.jdx.dev/tools/jsonschema
jsonschema = "17.0.0"
# https://mise-tools.jdx.dev/tools/lefthook
lefthook = "2.1.14"
# https://mise-tools.jdx.dev/tools/goreleaser
goreleaser = "2.18.2"
# https://github.com/oligot/go-mod-upgrade/releases
"github:oligot/go-mod-upgrade" = "0.12.0"
