language: go
go:
  - 1.16.3

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

script:
  - curl -sfL https://git.io/goreleaser | sh -s -- check
  - make test
  - if [[ -n "${TRAVIS_TAG}" ]]; then
    make release;
    fi


