language: go
go:
  - 1.12.5

env:
- GO111MODULE=on

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

script:
  - make test
  - if [[ -n "${TRAVIS_TAG}" ]]; then
    make release;
    fi


