language: go
go:
  - 1.16.3

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

script:
  - make test
  - curl -sfL https://git.io/goreleaser | sh -s -- check
  - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  - if [[ -n "${TRAVIS_TAG}" ]]; then
    ./bin/goreleaser --rm-dist;
    fi


