/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

// github.com/foomo/gotsrpc/v2/tests/common.Item
export interface Item {
	id:string;
	name:string;
}
// github.com/foomo/gotsrpc/v2/tests/common.Response
export interface Response<T> {
	data:T;
	error?:string;
}
// end of common js