/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

// github.com/foomo/gotsrpc/v2/tests/generics/server.Container
export interface Container<K extends string | number | symbol, V> {
	data:Record<K,V>|null;
	default:V;
}
// github.com/foomo/gotsrpc/v2/tests/generics/server.PagedResponse
export interface PagedResponse<T> {
	items:Array<T>|null;
	total:number;
}
// github.com/foomo/gotsrpc/v2/tests/generics/server.Pair
export interface Pair<A, B> {
	first:A;
	second:B;
}
// github.com/foomo/gotsrpc/v2/tests/generics/server.Result
export interface Result<T> {
	value?:T;
	error?:string;
}
// end of common js