/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

// github.com/foomo/gotsrpc/v3/tests/nested/server.Person
export interface Person {
	firstName:string;
	middleName:string;
	lastName:string;
	age:number;
}
// end of common js