/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as github_com_foomo_gotsrpc_v2 from './vo-gotsrpc'; // ./client/client.ts to ./client/vo-gotsrpc.ts

export class ServiceClient {
	public static defaultEndpoint = "/service";
	constructor(
		public transport:<T>(method: string, data?: any[]) => Promise<T>
	) {}
	async customError(msg:string):Promise<github_com_foomo_gotsrpc_v2.Error> {
		return (await this.transport<{0:github_com_foomo_gotsrpc_v2.Error}>("CustomError", [msg]))[0]
	}
	async error(msg:string):Promise<github_com_foomo_gotsrpc_v2.Error> {
		return (await this.transport<{0:github_com_foomo_gotsrpc_v2.Error}>("Error", [msg]))[0]
	}
	async hello(msg:string):Promise<string> {
		return (await this.transport<{0:string}>("Hello", [msg]))[0]
	}
	async joinedError(msg:string):Promise<github_com_foomo_gotsrpc_v2.Error> {
		return (await this.transport<{0:github_com_foomo_gotsrpc_v2.Error}>("JoinedError", [msg]))[0]
	}
	async pkgError(msg:string):Promise<github_com_foomo_gotsrpc_v2.Error> {
		return (await this.transport<{0:github_com_foomo_gotsrpc_v2.Error}>("PkgError", [msg]))[0]
	}
	async wrappedError(msg:string):Promise<github_com_foomo_gotsrpc_v2.Error> {
		return (await this.transport<{0:github_com_foomo_gotsrpc_v2.Error}>("WrappedError", [msg]))[0]
	}
}