/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as github_com_foomo_gotsrpc_v2_tests_nullable_server from './vo'; // ./client/vo.ts to ./client/vo.ts

// github.com/foomo/gotsrpc/v2/tests/nullable/server.ACustomType
export enum ACustomType {
	One = "one",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/nullable/server.ACustomTypes
export type ACustomTypes = Array<github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomType>
// github.com/foomo/gotsrpc/v2/tests/nullable/server.ACustomTypesMap
export type ACustomTypesMap = Record<github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomType,github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomType>
// github.com/foomo/gotsrpc/v2/tests/nullable/server.BCustomType
export type BCustomType = string
// github.com/foomo/gotsrpc/v2/tests/nullable/server.BCustomTypes
export type BCustomTypes = Array<github_com_foomo_gotsrpc_v2_tests_nullable_server.BCustomType>
// github.com/foomo/gotsrpc/v2/tests/nullable/server.BCustomTypesMap
export type BCustomTypesMap = Record<github_com_foomo_gotsrpc_v2_tests_nullable_server.BCustomType,github_com_foomo_gotsrpc_v2_tests_nullable_server.BCustomType>
// github.com/foomo/gotsrpc/v2/tests/nullable/server.Base
export interface Base {
	a1:github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested;
	a2?:github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested;
	a3:github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested|null;
	b1:string;
	b2?:string;
	b3:string|null;
	c1:any;
	c2?:any;
	c3:any;
	d1:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomType;
	d2?:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomType;
	d3:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomType|null;
	e1:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomTypes|null;
	e2?:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomTypes;
	e3:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomTypes|null;
	f1:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomTypesMap|null;
	f2?:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomTypesMap;
	f3:github_com_foomo_gotsrpc_v2_tests_nullable_server.ACustomTypesMap|null;
	Two:Array<github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested>|null;
	Two1:Array<Array<github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested>|null>|null;
	Two2:Array<Record<string,github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested>|null>|null;
	Three:Array<github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested|null>|null;
	Three1:Array<string|null>|null;
	Four:Record<string,github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested>|null;
	Five:Record<string,github_com_foomo_gotsrpc_v2_tests_nullable_server.Nested|null>|null;
	Six:{
		Foo:string;
	}|null;
}
// github.com/foomo/gotsrpc/v2/tests/nullable/server.Nested
export interface Nested {
	Foo:string;
}
// end of common js