// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package server

import (
	tls "crypto/tls"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	gorpcconv "github.com/foomo/gotsrpc/v3/semconv/gorpcconv"
	github_com_foomo_gotsrpc_v3_tests_common "github.com/foomo/gotsrpc/v3/tests/common"
	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
	instr  *gorpcconv.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config, opts ...gotsrpc.Option) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{
		instr: gorpcconv.NewClient(append([]gotsrpc.Option{gotsrpc.WithClientService("github.com/foomo/gotsrpc/v3/tests/nested-generics/server", "Service")}, opts...)...),
	}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) GetByKey(key string) (retGetByKey_0 int, clientErr error) {
	call := tsc.instr.Start("GetByKey")
	defer call.End()
	rpcReq := ServiceGetByKeyRequest{Key: key}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceGetByKeyResponse)
	return rpcResp.RetGetByKey_0, nil
}

func (tsc *ServiceGoRPCClient) GetName() (retGetName_0 string, clientErr error) {
	call := tsc.instr.Start("GetName")
	defer call.End()
	rpcReq := ServiceGetNameRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceGetNameResponse)
	return rpcResp.RetGetName_0, nil
}

func (tsc *ServiceGoRPCClient) GetValue() (retGetValue_0 github_com_foomo_gotsrpc_v3_tests_common.Item, clientErr error) {
	call := tsc.instr.Start("GetValue")
	defer call.End()
	rpcReq := ServiceGetValueRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceGetValueResponse)
	return rpcResp.RetGetValue_0, nil
}

func (tsc *ServiceGoRPCClient) GetWrapped() (retGetWrapped_0 github_com_foomo_gotsrpc_v3_tests_common.Response[github_com_foomo_gotsrpc_v3_tests_common.Item], clientErr error) {
	call := tsc.instr.Start("GetWrapped")
	defer call.End()
	rpcReq := ServiceGetWrappedRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceGetWrappedResponse)
	return rpcResp.RetGetWrapped_0, nil
}
