/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.

// github.com/foomo/gotsrpc/v2/example/time/service.TimeStruct
export interface TimeStruct {
	time:number;
	timePtr:number|null;
	timePtrOmit?:number;
}
// end of common js