// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	http "net/http"
	time "time"

	gotsrpc "github.com/foomo/gotsrpc/v2"
)

const (
	ServiceGoTSRPCProxyCategoryValue   = "CategoryValue"
	ServiceGoTSRPCProxyDataRecordNil   = "DataRecordNil"
	ServiceGoTSRPCProxyDataRecordValue = "DataRecordValue"
	ServiceGoTSRPCProxyDetailValue     = "DetailValue"
	ServiceGoTSRPCProxyEntriesValue    = "EntriesValue"
	ServiceGoTSRPCProxyEntryValue      = "EntryValue"
	ServiceGoTSRPCProxyIndexValue      = "IndexValue"
	ServiceGoTSRPCProxyLabelMapValue   = "LabelMapValue"
	ServiceGoTSRPCProxyMapOfEntries    = "MapOfEntries"
	ServiceGoTSRPCProxyPriorityValue   = "PriorityValue"
	ServiceGoTSRPCProxyRatingValue     = "RatingValue"
	ServiceGoTSRPCProxyRegistryValue   = "RegistryValue"
	ServiceGoTSRPCProxyStatusValue     = "StatusValue"
	ServiceGoTSRPCProxyTagsValue       = "TagsValue"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  Service
}

func NewDefaultServiceGoTSRPCProxy(service Service) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/service")
}

func NewServiceGoTSRPCProxy(service Service, endpoint string) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, _ := gotsrpc.GetStatsForRequest(r)
	if callStats != nil {
		callStats.Func = funcName
		callStats.Package = "github.com/foomo/gotsrpc/v2/tests/aliases/server"
		callStats.Service = "Service"
	}
	switch funcName {
	case ServiceGoTSRPCProxyCategoryValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Category
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		categoryValueRet := p.service.CategoryValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{categoryValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyDataRecordNil:
		var (
			args []any
			rets []any
		)
		var (
			arg_v DataRecord
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		dataRecordNilRet := p.service.DataRecordNil(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{dataRecordNilRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyDataRecordValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v DataRecord
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		dataRecordValueRet := p.service.DataRecordValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{dataRecordValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyDetailValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Detail
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		detailValueRet := p.service.DetailValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{detailValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyEntriesValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Entries
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		entriesValueRet := p.service.EntriesValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{entriesValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyEntryValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Entry
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		entryValueRet := p.service.EntryValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{entryValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyIndexValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Index
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		indexValueRet := p.service.IndexValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{indexValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyLabelMapValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v LabelMap
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		labelMapValueRet := p.service.LabelMapValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{labelMapValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyMapOfEntries:
		var (
			args []any
			rets []any
		)
		var (
			arg_v map[Category][]Entry
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		mapOfEntriesRet := p.service.MapOfEntries(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{mapOfEntriesRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyPriorityValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Priority
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		priorityValueRet := p.service.PriorityValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{priorityValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyRatingValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Rating
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		ratingValueRet := p.service.RatingValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{ratingValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyRegistryValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Registry
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		registryValueRet := p.service.RegistryValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{registryValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyStatusValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Status
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		statusValueRet := p.service.StatusValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{statusValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyTagsValue:
		var (
			args []any
			rets []any
		)
		var (
			arg_v Tags
		)
		args = []any{&arg_v}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		tagsValueRet := p.service.TagsValue(r.Context(), arg_v)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{tagsValueRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
