// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	go_context "context"
	go_net_http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	pkg_errors "github.com/pkg/errors"
)

type ServiceGoTSRPCClient interface {
	CategoryValue(ctx go_context.Context, v Category) (retCategoryValue_0 Category, clientErr error)
	DataRecordNil(ctx go_context.Context, v DataRecord) (retDataRecordNil_0 DataRecord, clientErr error)
	DataRecordValue(ctx go_context.Context, v DataRecord) (retDataRecordValue_0 DataRecord, clientErr error)
	DetailValue(ctx go_context.Context, v Detail) (retDetailValue_0 Detail, clientErr error)
	EntriesValue(ctx go_context.Context, v Entries) (retEntriesValue_0 Entries, clientErr error)
	EntryValue(ctx go_context.Context, v Entry) (retEntryValue_0 Entry, clientErr error)
	IndexValue(ctx go_context.Context, v Index) (retIndexValue_0 Index, clientErr error)
	LabelMapValue(ctx go_context.Context, v LabelMap) (retLabelMapValue_0 LabelMap, clientErr error)
	MapOfEntries(ctx go_context.Context, v map[Category][]Entry) (retMapOfEntries_0 map[Category][]Entry, clientErr error)
	PriorityValue(ctx go_context.Context, v Priority) (retPriorityValue_0 Priority, clientErr error)
	RatingValue(ctx go_context.Context, v Rating) (retRatingValue_0 Rating, clientErr error)
	RegistryValue(ctx go_context.Context, v Registry) (retRegistryValue_0 Registry, clientErr error)
	StatusValue(ctx go_context.Context, v Status) (retStatusValue_0 Status, clientErr error)
	TagsValue(ctx go_context.Context, v Tags) (retTagsValue_0 Tags, clientErr error)
}

type HTTPServiceGoTSRPCClient struct {
	URL      string
	EndPoint string
	Client   gotsrpc.Client
}

func NewDefaultServiceGoTSRPCClient(url string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClient(url, "/service")
}

func NewServiceGoTSRPCClient(url string, endpoint string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClientWithClient(url, endpoint, nil)
}

func NewServiceGoTSRPCClientWithClient(url string, endpoint string, client *go_net_http.Client) *HTTPServiceGoTSRPCClient {
	return &HTTPServiceGoTSRPCClient{
		URL:      url,
		EndPoint: endpoint,
		Client:   gotsrpc.NewClientWithHttpClient(client),
	}
}

func (tsc *HTTPServiceGoTSRPCClient) CategoryValue(ctx go_context.Context, v Category) (retCategoryValue_0 Category, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retCategoryValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "CategoryValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy CategoryValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) DataRecordNil(ctx go_context.Context, v DataRecord) (retDataRecordNil_0 DataRecord, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retDataRecordNil_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "DataRecordNil", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy DataRecordNil")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) DataRecordValue(ctx go_context.Context, v DataRecord) (retDataRecordValue_0 DataRecord, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retDataRecordValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "DataRecordValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy DataRecordValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) DetailValue(ctx go_context.Context, v Detail) (retDetailValue_0 Detail, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retDetailValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "DetailValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy DetailValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) EntriesValue(ctx go_context.Context, v Entries) (retEntriesValue_0 Entries, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retEntriesValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "EntriesValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy EntriesValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) EntryValue(ctx go_context.Context, v Entry) (retEntryValue_0 Entry, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retEntryValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "EntryValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy EntryValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) IndexValue(ctx go_context.Context, v Index) (retIndexValue_0 Index, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retIndexValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "IndexValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy IndexValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) LabelMapValue(ctx go_context.Context, v LabelMap) (retLabelMapValue_0 LabelMap, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retLabelMapValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "LabelMapValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy LabelMapValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) MapOfEntries(ctx go_context.Context, v map[Category][]Entry) (retMapOfEntries_0 map[Category][]Entry, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retMapOfEntries_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "MapOfEntries", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy MapOfEntries")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) PriorityValue(ctx go_context.Context, v Priority) (retPriorityValue_0 Priority, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retPriorityValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "PriorityValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy PriorityValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) RatingValue(ctx go_context.Context, v Rating) (retRatingValue_0 Rating, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retRatingValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "RatingValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy RatingValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) RegistryValue(ctx go_context.Context, v Registry) (retRegistryValue_0 Registry, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retRegistryValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "RegistryValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy RegistryValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) StatusValue(ctx go_context.Context, v Status) (retStatusValue_0 Status, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retStatusValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "StatusValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy StatusValue")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) TagsValue(ctx go_context.Context, v Tags) (retTagsValue_0 Tags, clientErr error) {
	rpcArgs := []any{v}
	rpcReply := []any{&retTagsValue_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "TagsValue", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy TagsValue")
	}
	return
}
