/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as github_com_foomo_gotsrpc_v2_tests_aliases_server from './vo'; // ./client/vo.ts to ./client/vo.ts

// github.com/foomo/gotsrpc/v2/tests/aliases/server.Category
export enum Category {
	A = "a",
	B = "b",
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Priority
export enum Priority {
	High = 3,
	Low = 1,
	Medium = 2,
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Status
export enum Status {
	Active = "active",
	Closed = "closed",
	Pending = "pending",
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Amount
export interface Amount {
	value:number;
	currency:string;
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.DataRecord
export interface DataRecord {
	id:string;
	title:string;
	status:github_com_foomo_gotsrpc_v2_tests_aliases_server.Status;
	amount?:github_com_foomo_gotsrpc_v2_tests_aliases_server.Amount;
	items?:github_com_foomo_gotsrpc_v2_tests_aliases_server.Entries;
	metadata?:github_com_foomo_gotsrpc_v2_tests_aliases_server.Metadata;
	categories?:Array<github_com_foomo_gotsrpc_v2_tests_aliases_server.Category>;
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Detail
export interface Detail {
	name:string;
	description:string;
	entry:github_com_foomo_gotsrpc_v2_tests_aliases_server.Entry;
	labels?:github_com_foomo_gotsrpc_v2_tests_aliases_server.LabelMap;
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Entries
export type Entries = Array<github_com_foomo_gotsrpc_v2_tests_aliases_server.Entry|null>
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Entry
export interface Entry {
	id:string;
	status:github_com_foomo_gotsrpc_v2_tests_aliases_server.Status;
	priority:github_com_foomo_gotsrpc_v2_tests_aliases_server.Priority;
	rating:github_com_foomo_gotsrpc_v2_tests_aliases_server.Rating;
	tags?:github_com_foomo_gotsrpc_v2_tests_aliases_server.Tags;
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Index
export type Index = Record<github_com_foomo_gotsrpc_v2_tests_aliases_server.Category,Array<github_com_foomo_gotsrpc_v2_tests_aliases_server.Entry>|null>
// github.com/foomo/gotsrpc/v2/tests/aliases/server.LabelMap
export type LabelMap = Record<string,string>
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Metadata
export interface Metadata {
	createdBy:string;
	note?:string;
}
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Rating
export type Rating = number
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Registry
export type Registry = Record<string,github_com_foomo_gotsrpc_v2_tests_aliases_server.Entry>
// github.com/foomo/gotsrpc/v2/tests/aliases/server.Tags
export type Tags = Array<string>
// end of common js