// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	tls "crypto/tls"

	gorpc "github.com/valyala/gorpc"
)

type ExtendedServiceGoRPCClient struct {
	Client *gorpc.Client
}

func NewExtendedServiceGoRPCClient(addr string, tlsConfig *tls.Config) *ExtendedServiceGoRPCClient {
	client := &ExtendedServiceGoRPCClient{}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ExtendedServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ExtendedServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ExtendedServiceGoRPCClient) GetAge() (retGetAge_0 int, clientErr error) {
	rpcReq := ExtendedServiceGetAgeRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ExtendedServiceGetAgeResponse)
	return rpcResp.RetGetAge_0, nil
}

func (tsc *ExtendedServiceGoRPCClient) GetFirstName() (retGetFirstName_0 string, clientErr error) {
	rpcReq := ExtendedServiceGetFirstNameRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ExtendedServiceGetFirstNameResponse)
	return rpcResp.RetGetFirstName_0, nil
}

func (tsc *ExtendedServiceGoRPCClient) GetLastName() (retGetLastName_0 string, clientErr error) {
	rpcReq := ExtendedServiceGetLastNameRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ExtendedServiceGetLastNameResponse)
	return rpcResp.RetGetLastName_0, nil
}

func (tsc *ExtendedServiceGoRPCClient) GetMiddleName() (retGetMiddleName_0 string, clientErr error) {
	rpcReq := ExtendedServiceGetMiddleNameRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ExtendedServiceGetMiddleNameResponse)
	return rpcResp.RetGetMiddleName_0, nil
}

func (tsc *ExtendedServiceGoRPCClient) GetPerson() (retGetPerson_0 Person, clientErr error) {
	rpcReq := ExtendedServiceGetPersonRequest{}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ExtendedServiceGetPersonResponse)
	return rpcResp.RetGetPerson_0, nil
}
