// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	go_context "context"
	tls "crypto/tls"
	gob "encoding/gob"
	fmt "fmt"
	reflect "reflect"
	strings "strings"
	time "time"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	gorpc "github.com/valyala/gorpc"
)

type (
	ExtendedServiceGoRPCProxy struct {
		server           *gorpc.Server
		service          ExtendedService
		callStatsHandler gotsrpc.GoRPCCallStatsHandlerFun
	}

	ExtendedServiceGetAgeRequest struct {
	}
	ExtendedServiceGetAgeResponse struct {
		RetGetAge_0 int
	}

	ExtendedServiceGetFirstNameRequest struct {
	}
	ExtendedServiceGetFirstNameResponse struct {
		RetGetFirstName_0 string
	}

	ExtendedServiceGetLastNameRequest struct {
	}
	ExtendedServiceGetLastNameResponse struct {
		RetGetLastName_0 string
	}

	ExtendedServiceGetMiddleNameRequest struct {
	}
	ExtendedServiceGetMiddleNameResponse struct {
		RetGetMiddleName_0 string
	}

	ExtendedServiceGetPersonRequest struct {
	}
	ExtendedServiceGetPersonResponse struct {
		RetGetPerson_0 Person
	}
)

func init() {
	gob.Register(ExtendedServiceGetAgeRequest{})
	gob.Register(ExtendedServiceGetAgeResponse{})
	gob.Register(ExtendedServiceGetFirstNameRequest{})
	gob.Register(ExtendedServiceGetFirstNameResponse{})
	gob.Register(ExtendedServiceGetLastNameRequest{})
	gob.Register(ExtendedServiceGetLastNameResponse{})
	gob.Register(ExtendedServiceGetMiddleNameRequest{})
	gob.Register(ExtendedServiceGetMiddleNameResponse{})
	gob.Register(ExtendedServiceGetPersonRequest{})
	gob.Register(ExtendedServiceGetPersonResponse{})
}

func NewExtendedServiceGoRPCProxy(addr string, service ExtendedService, tlsConfig *tls.Config) *ExtendedServiceGoRPCProxy {
	proxy := &ExtendedServiceGoRPCProxy{
		service: service,
	}

	if tlsConfig != nil {
		proxy.server = gorpc.NewTLSServer(addr, proxy.handler, tlsConfig)
	} else {
		proxy.server = gorpc.NewTCPServer(addr, proxy.handler)
	}

	return proxy
}

func (p *ExtendedServiceGoRPCProxy) Start() error {
	return p.server.Start()
}

func (p *ExtendedServiceGoRPCProxy) Serve() error {
	return p.server.Serve()
}

func (p *ExtendedServiceGoRPCProxy) Stop() {
	p.server.Stop()
}

func (p *ExtendedServiceGoRPCProxy) SetCallStatsHandler(handler gotsrpc.GoRPCCallStatsHandlerFun) {
	p.callStatsHandler = handler
}

func (p *ExtendedServiceGoRPCProxy) handler(clientAddr string, request any) (response any) {
	var start time.Time
	if p.callStatsHandler != nil {
		start = time.Now()
	}

	reqType := reflect.TypeOf(request).String()
	funcNameParts := strings.Split(reqType, ".")
	funcName := funcNameParts[len(funcNameParts)-1]

	switch funcName {
	case "ExtendedServiceGetAgeRequest":
		retGetAge_0 := p.service.GetAge(go_context.Background())
		response = ExtendedServiceGetAgeResponse{RetGetAge_0: retGetAge_0}
	case "ExtendedServiceGetFirstNameRequest":
		retGetFirstName_0 := p.service.GetFirstName(go_context.Background())
		response = ExtendedServiceGetFirstNameResponse{RetGetFirstName_0: retGetFirstName_0}
	case "ExtendedServiceGetLastNameRequest":
		retGetLastName_0 := p.service.GetLastName(go_context.Background())
		response = ExtendedServiceGetLastNameResponse{RetGetLastName_0: retGetLastName_0}
	case "ExtendedServiceGetMiddleNameRequest":
		retGetMiddleName_0 := p.service.GetMiddleName(go_context.Background())
		response = ExtendedServiceGetMiddleNameResponse{RetGetMiddleName_0: retGetMiddleName_0}
	case "ExtendedServiceGetPersonRequest":
		retGetPerson_0 := p.service.GetPerson(go_context.Background())
		response = ExtendedServiceGetPersonResponse{RetGetPerson_0: retGetPerson_0}
	default:
		fmt.Println("Unknown request type", reflect.TypeOf(request).String())
	}

	if p.callStatsHandler != nil {
		p.callStatsHandler(&gotsrpc.CallStats{
			Func:      funcName,
			Package:   "github.com/foomo/gotsrpc/v2/tests/nested/server",
			Service:   "ExtendedService",
			Execution: time.Since(start),
		})
	}

	return
}
