// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package server

import (
	"io"
	http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	httpconv "github.com/foomo/gotsrpc/v3/semconv/httpconv"
)

const (
	ExtendedServiceGoTSRPCProxyGetAge        = "GetAge"
	ExtendedServiceGoTSRPCProxyGetFirstName  = "GetFirstName"
	ExtendedServiceGoTSRPCProxyGetLastName   = "GetLastName"
	ExtendedServiceGoTSRPCProxyGetMiddleName = "GetMiddleName"
	ExtendedServiceGoTSRPCProxyGetPerson     = "GetPerson"
)

type ExtendedServiceGoTSRPCProxy struct {
	EndPoint string
	service  ExtendedService
	instr    *httpconv.Server
}

func NewDefaultExtendedServiceGoTSRPCProxy(service ExtendedService, opts ...gotsrpc.Option) *ExtendedServiceGoTSRPCProxy {
	return NewExtendedServiceGoTSRPCProxy(service, "/service", opts...)
}

func NewExtendedServiceGoTSRPCProxy(service ExtendedService, endpoint string, opts ...gotsrpc.Option) *ExtendedServiceGoTSRPCProxy {
	return &ExtendedServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
		instr:    httpconv.NewServer("github.com/foomo/gotsrpc/v3/tests/nested/server", "ExtendedService", opts...),
	}
}

// ServeHTTP exposes your service
func (p *ExtendedServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	r, call := p.instr.Start(w, r, funcName)
	defer call.End()
	switch funcName {
	case ExtendedServiceGoTSRPCProxyGetAge:
		var rets []any
		call.ExecutionStart()
		getAgeRet := p.service.GetAge(r.Context())
		call.ExecutionEnd()
		rets = []any{getAgeRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ExtendedServiceGoTSRPCProxyGetFirstName:
		var rets []any
		call.ExecutionStart()
		getFirstNameRet := p.service.GetFirstName(r.Context())
		call.ExecutionEnd()
		rets = []any{getFirstNameRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ExtendedServiceGoTSRPCProxyGetLastName:
		var rets []any
		call.ExecutionStart()
		getLastNameRet := p.service.GetLastName(r.Context())
		call.ExecutionEnd()
		rets = []any{getLastNameRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ExtendedServiceGoTSRPCProxyGetMiddleName:
		var rets []any
		call.ExecutionStart()
		getMiddleNameRet := p.service.GetMiddleName(r.Context())
		call.ExecutionEnd()
		rets = []any{getMiddleNameRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ExtendedServiceGoTSRPCProxyGetPerson:
		var rets []any
		call.ExecutionStart()
		getPersonRet := p.service.GetPerson(r.Context())
		call.ExecutionEnd()
		rets = []any{getPersonRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	default:
		call.NotFound()
		gotsrpc.ErrorFuncNotFound(w)
	}
}
