// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	go_context "context"
	go_net_http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	pkg_errors "github.com/pkg/errors"
)

type ExtendedServiceGoTSRPCClient interface {
	GetAge(ctx go_context.Context) (retGetAge_0 int, clientErr error)
	GetFirstName(ctx go_context.Context) (retGetFirstName_0 string, clientErr error)
	GetLastName(ctx go_context.Context) (retGetLastName_0 string, clientErr error)
	GetMiddleName(ctx go_context.Context) (retGetMiddleName_0 string, clientErr error)
	GetPerson(ctx go_context.Context) (retGetPerson_0 Person, clientErr error)
}

type HTTPExtendedServiceGoTSRPCClient struct {
	URL      string
	EndPoint string
	Client   gotsrpc.Client
}

func NewDefaultExtendedServiceGoTSRPCClient(url string) *HTTPExtendedServiceGoTSRPCClient {
	return NewExtendedServiceGoTSRPCClient(url, "/service")
}

func NewExtendedServiceGoTSRPCClient(url string, endpoint string) *HTTPExtendedServiceGoTSRPCClient {
	return NewExtendedServiceGoTSRPCClientWithClient(url, endpoint, nil)
}

func NewExtendedServiceGoTSRPCClientWithClient(url string, endpoint string, client *go_net_http.Client) *HTTPExtendedServiceGoTSRPCClient {
	return &HTTPExtendedServiceGoTSRPCClient{
		URL:      url,
		EndPoint: endpoint,
		Client:   gotsrpc.NewClientWithHttpClient(client),
	}
}

func (tsc *HTTPExtendedServiceGoTSRPCClient) GetAge(ctx go_context.Context) (retGetAge_0 int, clientErr error) {
	rpcArgs := []any{}
	rpcReply := []any{&retGetAge_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "GetAge", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ExtendedServiceGoTSRPCProxy GetAge")
	}
	return
}

func (tsc *HTTPExtendedServiceGoTSRPCClient) GetFirstName(ctx go_context.Context) (retGetFirstName_0 string, clientErr error) {
	rpcArgs := []any{}
	rpcReply := []any{&retGetFirstName_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "GetFirstName", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ExtendedServiceGoTSRPCProxy GetFirstName")
	}
	return
}

func (tsc *HTTPExtendedServiceGoTSRPCClient) GetLastName(ctx go_context.Context) (retGetLastName_0 string, clientErr error) {
	rpcArgs := []any{}
	rpcReply := []any{&retGetLastName_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "GetLastName", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ExtendedServiceGoTSRPCProxy GetLastName")
	}
	return
}

func (tsc *HTTPExtendedServiceGoTSRPCClient) GetMiddleName(ctx go_context.Context) (retGetMiddleName_0 string, clientErr error) {
	rpcArgs := []any{}
	rpcReply := []any{&retGetMiddleName_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "GetMiddleName", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ExtendedServiceGoTSRPCProxy GetMiddleName")
	}
	return
}

func (tsc *HTTPExtendedServiceGoTSRPCClient) GetPerson(ctx go_context.Context) (retGetPerson_0 Person, clientErr error) {
	rpcArgs := []any{}
	rpcReply := []any{&retGetPerson_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "GetPerson", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ExtendedServiceGoTSRPCProxy GetPerson")
	}
	return
}
