// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package server

import (
	tls "crypto/tls"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	gorpcconv "github.com/foomo/gotsrpc/v3/semconv/gorpcconv"
	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
	instr  *gorpcconv.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config, opts ...gotsrpc.Option) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{
		instr: gorpcconv.NewClient(append([]gotsrpc.Option{gotsrpc.WithClientService("github.com/foomo/gotsrpc/v3/tests/context/server", "Service")}, opts...)...),
	}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) CustomError(msg string) (retCustomError_0 error, clientErr error) {
	call := tsc.instr.Start("CustomError")
	defer call.End()
	rpcReq := ServiceCustomErrorRequest{Msg: msg}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceCustomErrorResponse)
	return rpcResp.RetCustomError_0, nil
}

func (tsc *ServiceGoRPCClient) Error(msg string) (retError_0 error, clientErr error) {
	call := tsc.instr.Start("Error")
	defer call.End()
	rpcReq := ServiceErrorRequest{Msg: msg}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceErrorResponse)
	return rpcResp.RetError_0, nil
}

func (tsc *ServiceGoRPCClient) Hello(msg string) (retHello_0 string, clientErr error) {
	call := tsc.instr.Start("Hello")
	defer call.End()
	rpcReq := ServiceHelloRequest{Msg: msg}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceHelloResponse)
	return rpcResp.RetHello_0, nil
}

func (tsc *ServiceGoRPCClient) JoinedError(msg string) (retJoinedError_0 error, clientErr error) {
	call := tsc.instr.Start("JoinedError")
	defer call.End()
	rpcReq := ServiceJoinedErrorRequest{Msg: msg}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceJoinedErrorResponse)
	return rpcResp.RetJoinedError_0, nil
}

func (tsc *ServiceGoRPCClient) PkgError(msg string) (retPkgError_0 error, clientErr error) {
	call := tsc.instr.Start("PkgError")
	defer call.End()
	rpcReq := ServicePkgErrorRequest{Msg: msg}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServicePkgErrorResponse)
	return rpcResp.RetPkgError_0, nil
}

func (tsc *ServiceGoRPCClient) WrappedError(msg string) (retWrappedError_0 error, clientErr error) {
	call := tsc.instr.Start("WrappedError")
	defer call.End()
	rpcReq := ServiceWrappedErrorRequest{Msg: msg}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		call.RecordError(rpcErr, 0)
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceWrappedErrorResponse)
	return rpcResp.RetWrappedError_0, nil
}
