// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

package server

import (
	"io"
	http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v3"
	httpconv "github.com/foomo/gotsrpc/v3/semconv/httpconv"
)

const (
	ServiceGoTSRPCProxyCustomError  = "CustomError"
	ServiceGoTSRPCProxyError        = "Error"
	ServiceGoTSRPCProxyHello        = "Hello"
	ServiceGoTSRPCProxyJoinedError  = "JoinedError"
	ServiceGoTSRPCProxyPkgError     = "PkgError"
	ServiceGoTSRPCProxyWrappedError = "WrappedError"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  Service
	instr    *httpconv.Server
}

func NewDefaultServiceGoTSRPCProxy(service Service, opts ...gotsrpc.Option) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/service", opts...)
}

func NewServiceGoTSRPCProxy(service Service, endpoint string, opts ...gotsrpc.Option) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
		instr:    httpconv.NewServer("github.com/foomo/gotsrpc/v3/tests/context/server", "Service", opts...),
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	r, call := p.instr.Start(w, r, funcName)
	defer call.End()
	switch funcName {
	case ServiceGoTSRPCProxyCustomError:
		var rets []any
		var (
			arg_msg string
		)
		args := []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		customErrorRet := p.service.CustomError(r.Context(), arg_msg)
		call.ExecutionEnd()
		rets = []any{gotsrpc.ErrorReply(customErrorRet)}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ServiceGoTSRPCProxyError:
		var rets []any
		var (
			arg_msg string
		)
		args := []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		errorRet := p.service.Error(r.Context(), arg_msg)
		call.ExecutionEnd()
		rets = []any{gotsrpc.ErrorReply(errorRet)}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ServiceGoTSRPCProxyHello:
		var rets []any
		var (
			arg_msg string
		)
		args := []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		helloRet := p.service.Hello(r.Context(), arg_msg)
		call.ExecutionEnd()
		rets = []any{helloRet}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ServiceGoTSRPCProxyJoinedError:
		var rets []any
		var (
			arg_msg string
		)
		args := []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		joinedErrorRet := p.service.JoinedError(r.Context(), arg_msg)
		call.ExecutionEnd()
		rets = []any{gotsrpc.ErrorReply(joinedErrorRet)}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ServiceGoTSRPCProxyPkgError:
		var rets []any
		var (
			arg_msg string
		)
		args := []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		pkgErrorRet := p.service.PkgError(r.Context(), arg_msg)
		call.ExecutionEnd()
		rets = []any{gotsrpc.ErrorReply(pkgErrorRet)}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	case ServiceGoTSRPCProxyWrappedError:
		var rets []any
		var (
			arg_msg string
		)
		args := []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, call, r); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		call.ExecutionStart()
		wrappedErrorRet := p.service.WrappedError(r.Context(), arg_msg)
		call.ExecutionEnd()
		rets = []any{gotsrpc.ErrorReply(wrappedErrorRet)}
		if err := gotsrpc.Reply(rets, call, r, w); err != nil {
			call.SetError(err)
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		return
	default:
		call.NotFound()
		gotsrpc.ErrorFuncNotFound(w)
	}
}
