// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	http "net/http"
	time "time"

	gotsrpc "github.com/foomo/gotsrpc/v2"
)

const (
	ServiceGoTSRPCProxyCustomError  = "CustomError"
	ServiceGoTSRPCProxyError        = "Error"
	ServiceGoTSRPCProxyHello        = "Hello"
	ServiceGoTSRPCProxyJoinedError  = "JoinedError"
	ServiceGoTSRPCProxyPkgError     = "PkgError"
	ServiceGoTSRPCProxyWrappedError = "WrappedError"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  Service
}

func NewDefaultServiceGoTSRPCProxy(service Service) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/service")
}

func NewServiceGoTSRPCProxy(service Service, endpoint string) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, _ := gotsrpc.GetStatsForRequest(r)
	if callStats != nil {
		callStats.Func = funcName
		callStats.Package = "github.com/foomo/gotsrpc/v2/tests/context/server"
		callStats.Service = "Service"
	}
	switch funcName {
	case ServiceGoTSRPCProxyCustomError:
		var (
			args []any
			rets []any
		)
		var (
			arg_msg string
		)
		args = []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		customErrorRet := p.service.CustomError(r.Context(), arg_msg)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{gotsrpc.ErrorReply(customErrorRet)}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyError:
		var (
			args []any
			rets []any
		)
		var (
			arg_msg string
		)
		args = []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		errorRet := p.service.Error(r.Context(), arg_msg)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{gotsrpc.ErrorReply(errorRet)}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyHello:
		var (
			args []any
			rets []any
		)
		var (
			arg_msg string
		)
		args = []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		helloRet := p.service.Hello(r.Context(), arg_msg)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{helloRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyJoinedError:
		var (
			args []any
			rets []any
		)
		var (
			arg_msg string
		)
		args = []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		joinedErrorRet := p.service.JoinedError(r.Context(), arg_msg)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{gotsrpc.ErrorReply(joinedErrorRet)}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyPkgError:
		var (
			args []any
			rets []any
		)
		var (
			arg_msg string
		)
		args = []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		pkgErrorRet := p.service.PkgError(r.Context(), arg_msg)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{gotsrpc.ErrorReply(pkgErrorRet)}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyWrappedError:
		var (
			args []any
			rets []any
		)
		var (
			arg_msg string
		)
		args = []any{&arg_msg}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		var executionStart time.Time
		if callStats != nil {
			executionStart = time.Now()
		}
		wrappedErrorRet := p.service.WrappedError(r.Context(), arg_msg)
		if callStats != nil {
			callStats.Execution = time.Since(executionStart)
		}
		rets = []any{gotsrpc.ErrorReply(wrappedErrorRet)}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
