// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.

package server

import (
	go_context "context"
	go_net_http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	pkg_errors "github.com/pkg/errors"
)

type ServiceGoTSRPCClient interface {
	CustomError(ctx go_context.Context, msg string) (retCustomError_0 error, clientErr error)
	Error(ctx go_context.Context, msg string) (retError_0 error, clientErr error)
	Hello(ctx go_context.Context, msg string) (retHello_0 string, clientErr error)
	JoinedError(ctx go_context.Context, msg string) (retJoinedError_0 error, clientErr error)
	PkgError(ctx go_context.Context, msg string) (retPkgError_0 error, clientErr error)
	WrappedError(ctx go_context.Context, msg string) (retWrappedError_0 error, clientErr error)
}

type HTTPServiceGoTSRPCClient struct {
	URL      string
	EndPoint string
	Client   gotsrpc.Client
}

func NewDefaultServiceGoTSRPCClient(url string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClient(url, "/service")
}

func NewServiceGoTSRPCClient(url string, endpoint string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClientWithClient(url, endpoint, nil)
}

func NewServiceGoTSRPCClientWithClient(url string, endpoint string, client *go_net_http.Client) *HTTPServiceGoTSRPCClient {
	return &HTTPServiceGoTSRPCClient{
		URL:      url,
		EndPoint: endpoint,
		Client:   gotsrpc.NewClientWithHttpClient(client),
	}
}

func (tsc *HTTPServiceGoTSRPCClient) CustomError(ctx go_context.Context, msg string) (retCustomError_0 error, clientErr error) {
	rpcArgs := []any{msg}
	rpcReply := []any{&retCustomError_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "CustomError", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy CustomError")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) Error(ctx go_context.Context, msg string) (retError_0 error, clientErr error) {
	rpcArgs := []any{msg}
	rpcReply := []any{&retError_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "Error", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy Error")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) Hello(ctx go_context.Context, msg string) (retHello_0 string, clientErr error) {
	rpcArgs := []any{msg}
	rpcReply := []any{&retHello_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "Hello", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy Hello")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) JoinedError(ctx go_context.Context, msg string) (retJoinedError_0 error, clientErr error) {
	rpcArgs := []any{msg}
	rpcReply := []any{&retJoinedError_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "JoinedError", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy JoinedError")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) PkgError(ctx go_context.Context, msg string) (retPkgError_0 error, clientErr error) {
	rpcArgs := []any{msg}
	rpcReply := []any{&retPkgError_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "PkgError", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy PkgError")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) WrappedError(ctx go_context.Context, msg string) (retWrappedError_0 error, clientErr error) {
	rpcArgs := []any{msg}
	rpcReply := []any{&retWrappedError_0}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "WrappedError", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call server.ServiceGoTSRPCProxy WrappedError")
	}
	return
}
