/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.
import * as time from './vo-time_gen'; // ./client/src/vo-time_gen.ts to ./client/src/vo-time_gen.ts

// time.Time
export interface Time {
}
// end of common js