module:
  name: github.com/foomo/gotsrpc/v2
  path: ../

targets:
  demo:
    services:
      /service/foo: Foo
      /service/bar: Bar
      /service/demo: Demo
    package: github.com/foomo/gotsrpc/v2/demo
    out: demo/output/client.ts
    gorpc:
      - Foo
      - Bar
      - Demo
    tsrpc:
      - Foo
      - Bar
      - Demo

mappings:
  github.com/foomo/gotsrpc/v2/demo:
    out: demo/output/demo.ts
  github.com/foomo/gotsrpc/v2/demo/nested:
    out: demo/output/demo-nested.ts
...