// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.

package service

import (
	tls "crypto/tls"

	gorpc "github.com/valyala/gorpc"
)

type ServiceGoRPCClient struct {
	Client *gorpc.Client
}

func NewServiceGoRPCClient(addr string, tlsConfig *tls.Config) *ServiceGoRPCClient {
	client := &ServiceGoRPCClient{}
	if tlsConfig == nil {
		client.Client = gorpc.NewTCPClient(addr)
	} else {
		client.Client = gorpc.NewTLSClient(addr, tlsConfig)
	}
	return client
}

func (tsc *ServiceGoRPCClient) Start() {
	tsc.Client.Start()
}

func (tsc *ServiceGoRPCClient) Stop() {
	tsc.Client.Stop()
}

func (tsc *ServiceGoRPCClient) Bool(v bool) (retBool_0 bool, clientErr error) {
	rpcReq := ServiceBoolRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolResponse)
	return rpcResp.RetBool_0, nil
}

func (tsc *ServiceGoRPCClient) BoolPtr(v bool) (retBoolPtr_0 *bool, clientErr error) {
	rpcReq := ServiceBoolPtrRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolPtrResponse)
	return rpcResp.RetBoolPtr_0, nil
}

func (tsc *ServiceGoRPCClient) BoolSlice(v []bool) (retBoolSlice_0 []bool, clientErr error) {
	rpcReq := ServiceBoolSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceBoolSliceResponse)
	return rpcResp.RetBoolSlice_0, nil
}

func (tsc *ServiceGoRPCClient) Context() (clientErr error) {
	rpcReq := ServiceContextRequest{}
	_, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	return nil
}

func (tsc *ServiceGoRPCClient) Empty() (clientErr error) {
	rpcReq := ServiceEmptyRequest{}
	_, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	return nil
}

func (tsc *ServiceGoRPCClient) Float32(v float32) (retFloat32_0 float32, clientErr error) {
	rpcReq := ServiceFloat32Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32Response)
	return rpcResp.RetFloat32_0, nil
}

func (tsc *ServiceGoRPCClient) Float32Map(v map[float32]any) (retFloat32Map_0 map[float32]any, clientErr error) {
	rpcReq := ServiceFloat32MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32MapResponse)
	return rpcResp.RetFloat32Map_0, nil
}

func (tsc *ServiceGoRPCClient) Float32Slice(v []float32) (retFloat32Slice_0 []float32, clientErr error) {
	rpcReq := ServiceFloat32SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32SliceResponse)
	return rpcResp.RetFloat32Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Float32Type(v Float32Type) (retFloat32Type_0 Float32Type, clientErr error) {
	rpcReq := ServiceFloat32TypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32TypeResponse)
	return rpcResp.RetFloat32Type_0, nil
}

func (tsc *ServiceGoRPCClient) Float32TypeMap(v map[Float32TypeMapKey]Float32TypeMapValue) (retFloat32TypeMap_0 map[Float32TypeMapKey]Float32TypeMapValue, clientErr error) {
	rpcReq := ServiceFloat32TypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32TypeMapResponse)
	return rpcResp.RetFloat32TypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) Float32TypeMapTyped(v Float32TypeMapTyped) (retFloat32TypeMapTyped_0 Float32TypeMapTyped, clientErr error) {
	rpcReq := ServiceFloat32TypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat32TypeMapTypedResponse)
	return rpcResp.RetFloat32TypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) Float64(v float64) (retFloat64_0 float64, clientErr error) {
	rpcReq := ServiceFloat64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64Response)
	return rpcResp.RetFloat64_0, nil
}

func (tsc *ServiceGoRPCClient) Float64Map(v map[float64]any) (retFloat64Map_0 map[float64]any, clientErr error) {
	rpcReq := ServiceFloat64MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64MapResponse)
	return rpcResp.RetFloat64Map_0, nil
}

func (tsc *ServiceGoRPCClient) Float64Slice(v []float64) (retFloat64Slice_0 []float64, clientErr error) {
	rpcReq := ServiceFloat64SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64SliceResponse)
	return rpcResp.RetFloat64Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Float64Type(v Float64Type) (retFloat64Type_0 Float64Type, clientErr error) {
	rpcReq := ServiceFloat64TypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64TypeResponse)
	return rpcResp.RetFloat64Type_0, nil
}

func (tsc *ServiceGoRPCClient) Float64TypeMap(v map[Float64TypeMapKey]Float64TypeMapValue) (retFloat64TypeMap_0 map[Float64TypeMapKey]Float64TypeMapValue, clientErr error) {
	rpcReq := ServiceFloat64TypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64TypeMapResponse)
	return rpcResp.RetFloat64TypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) Float64TypeMapTyped(v Float64TypeMapTyped) (retFloat64TypeMapTyped_0 Float64TypeMapTyped, clientErr error) {
	rpcReq := ServiceFloat64TypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceFloat64TypeMapTypedResponse)
	return rpcResp.RetFloat64TypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) Int(v int) (retInt_0 int, clientErr error) {
	rpcReq := ServiceIntRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntResponse)
	return rpcResp.RetInt_0, nil
}

func (tsc *ServiceGoRPCClient) Int32(v int32) (retInt32_0 int32, clientErr error) {
	rpcReq := ServiceInt32Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32Response)
	return rpcResp.RetInt32_0, nil
}

func (tsc *ServiceGoRPCClient) Int32Map(v map[int32]any) (retInt32Map_0 map[int32]any, clientErr error) {
	rpcReq := ServiceInt32MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32MapResponse)
	return rpcResp.RetInt32Map_0, nil
}

func (tsc *ServiceGoRPCClient) Int32Slice(v []int32) (retInt32Slice_0 []int32, clientErr error) {
	rpcReq := ServiceInt32SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32SliceResponse)
	return rpcResp.RetInt32Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Int32Type(v Int32Type) (retInt32Type_0 Int32Type, clientErr error) {
	rpcReq := ServiceInt32TypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32TypeResponse)
	return rpcResp.RetInt32Type_0, nil
}

func (tsc *ServiceGoRPCClient) Int32TypeMap(v map[Int32TypeMapKey]Int32TypeMapValue) (retInt32TypeMap_0 map[Int32TypeMapKey]Int32TypeMapValue, clientErr error) {
	rpcReq := ServiceInt32TypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32TypeMapResponse)
	return rpcResp.RetInt32TypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) Int32TypeMapTyped(v Int32TypeMapTyped) (retInt32TypeMapTyped_0 Int32TypeMapTyped, clientErr error) {
	rpcReq := ServiceInt32TypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt32TypeMapTypedResponse)
	return rpcResp.RetInt32TypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) Int64(v int64) (retInt64_0 int64, clientErr error) {
	rpcReq := ServiceInt64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64Response)
	return rpcResp.RetInt64_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Map(v map[int64]any) (retInt64Map_0 map[int64]any, clientErr error) {
	rpcReq := ServiceInt64MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64MapResponse)
	return rpcResp.RetInt64Map_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Slice(v []int64) (retInt64Slice_0 []int64, clientErr error) {
	rpcReq := ServiceInt64SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64SliceResponse)
	return rpcResp.RetInt64Slice_0, nil
}

func (tsc *ServiceGoRPCClient) Int64Type(v Int64Type) (retInt64Type_0 Int64Type, clientErr error) {
	rpcReq := ServiceInt64TypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64TypeResponse)
	return rpcResp.RetInt64Type_0, nil
}

func (tsc *ServiceGoRPCClient) Int64TypeMap(v map[Int64TypeMapKey]Int64TypeMapValue) (retInt64TypeMap_0 map[Int64TypeMapKey]Int64TypeMapValue, clientErr error) {
	rpcReq := ServiceInt64TypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64TypeMapResponse)
	return rpcResp.RetInt64TypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) Int64TypeMapTyped(v Int64TypeMapTyped) (retInt64TypeMapTyped_0 Int64TypeMapTyped, clientErr error) {
	rpcReq := ServiceInt64TypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInt64TypeMapTypedResponse)
	return rpcResp.RetInt64TypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) IntMap(v map[int]any) (retIntMap_0 map[int]any, clientErr error) {
	rpcReq := ServiceIntMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntMapResponse)
	return rpcResp.RetIntMap_0, nil
}

func (tsc *ServiceGoRPCClient) IntSlice(v []int) (retIntSlice_0 []int, clientErr error) {
	rpcReq := ServiceIntSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntSliceResponse)
	return rpcResp.RetIntSlice_0, nil
}

func (tsc *ServiceGoRPCClient) IntType(v IntType) (retIntType_0 IntType, clientErr error) {
	rpcReq := ServiceIntTypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntTypeResponse)
	return rpcResp.RetIntType_0, nil
}

func (tsc *ServiceGoRPCClient) IntTypeMap(v map[IntTypeMapKey]IntTypeMapValue) (retIntTypeMap_0 map[IntTypeMapKey]IntTypeMapValue, clientErr error) {
	rpcReq := ServiceIntTypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntTypeMapResponse)
	return rpcResp.RetIntTypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) IntTypeMapTyped(v IntTypeMapTyped) (retIntTypeMapTyped_0 IntTypeMapTyped, clientErr error) {
	rpcReq := ServiceIntTypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceIntTypeMapTypedResponse)
	return rpcResp.RetIntTypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) Interface(v any) (retInterface_0 any, clientErr error) {
	rpcReq := ServiceInterfaceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInterfaceResponse)
	return rpcResp.RetInterface_0, nil
}

func (tsc *ServiceGoRPCClient) InterfaceSlice(v []any) (retInterfaceSlice_0 []any, clientErr error) {
	rpcReq := ServiceInterfaceSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceInterfaceSliceResponse)
	return rpcResp.RetInterfaceSlice_0, nil
}

func (tsc *ServiceGoRPCClient) NestedType(v NestedType) (retNestedType_0 NestedType, clientErr error) {
	rpcReq := ServiceNestedTypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceNestedTypeResponse)
	return rpcResp.RetNestedType_0, nil
}

func (tsc *ServiceGoRPCClient) String(v string) (retString_0 string, clientErr error) {
	rpcReq := ServiceStringRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringResponse)
	return rpcResp.RetString_0, nil
}

func (tsc *ServiceGoRPCClient) StringMap(v map[string]any) (retStringMap_0 map[string]any, clientErr error) {
	rpcReq := ServiceStringMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringMapResponse)
	return rpcResp.RetStringMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringSlice(v []string) (retStringSlice_0 []string, clientErr error) {
	rpcReq := ServiceStringSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringSliceResponse)
	return rpcResp.RetStringSlice_0, nil
}

func (tsc *ServiceGoRPCClient) StringType(v StringType) (retStringType_0 StringType, clientErr error) {
	rpcReq := ServiceStringTypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringTypeResponse)
	return rpcResp.RetStringType_0, nil
}

func (tsc *ServiceGoRPCClient) StringTypeMap(v map[StringTypeMapKey]StringTypeMapValue) (retStringTypeMap_0 map[StringTypeMapKey]StringTypeMapValue, clientErr error) {
	rpcReq := ServiceStringTypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringTypeMapResponse)
	return rpcResp.RetStringTypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) StringTypeMapTyped(v StringTypeMapTyped) (retStringTypeMapTyped_0 StringTypeMapTyped, clientErr error) {
	rpcReq := ServiceStringTypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStringTypeMapTypedResponse)
	return rpcResp.RetStringTypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) Struct(v Struct) (retStruct_0 Struct, clientErr error) {
	rpcReq := ServiceStructRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceStructResponse)
	return rpcResp.RetStruct_0, nil
}

func (tsc *ServiceGoRPCClient) UInt(v uint) (retUInt_0 uint, clientErr error) {
	rpcReq := ServiceUIntRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUIntResponse)
	return rpcResp.RetUInt_0, nil
}

func (tsc *ServiceGoRPCClient) UInt32(v uint32) (retUInt32_0 uint32, clientErr error) {
	rpcReq := ServiceUInt32Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt32Response)
	return rpcResp.RetUInt32_0, nil
}

func (tsc *ServiceGoRPCClient) UInt32Map(v map[uint32]any) (retUInt32Map_0 map[uint32]any, clientErr error) {
	rpcReq := ServiceUInt32MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt32MapResponse)
	return rpcResp.RetUInt32Map_0, nil
}

func (tsc *ServiceGoRPCClient) UInt32Slice(v []uint32) (retUInt32Slice_0 []uint32, clientErr error) {
	rpcReq := ServiceUInt32SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt32SliceResponse)
	return rpcResp.RetUInt32Slice_0, nil
}

func (tsc *ServiceGoRPCClient) UInt32Type(v UInt32Type) (retUInt32Type_0 UInt32Type, clientErr error) {
	rpcReq := ServiceUInt32TypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt32TypeResponse)
	return rpcResp.RetUInt32Type_0, nil
}

func (tsc *ServiceGoRPCClient) UInt32TypeMap(v map[UInt32TypeMapKey]UInt32TypeMapValue) (retUInt32TypeMap_0 map[UInt32TypeMapKey]UInt32TypeMapValue, clientErr error) {
	rpcReq := ServiceUInt32TypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt32TypeMapResponse)
	return rpcResp.RetUInt32TypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) UInt32TypeMapTyped(v UInt32TypeMapTyped) (retUInt32TypeMapTyped_0 UInt32TypeMapTyped, clientErr error) {
	rpcReq := ServiceUInt32TypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt32TypeMapTypedResponse)
	return rpcResp.RetUInt32TypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) UInt64(v uint64) (retUInt64_0 uint64, clientErr error) {
	rpcReq := ServiceUInt64Request{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt64Response)
	return rpcResp.RetUInt64_0, nil
}

func (tsc *ServiceGoRPCClient) UInt64Map(v map[uint64]any) (retUInt64Map_0 map[uint64]any, clientErr error) {
	rpcReq := ServiceUInt64MapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt64MapResponse)
	return rpcResp.RetUInt64Map_0, nil
}

func (tsc *ServiceGoRPCClient) UInt64Slice(v []uint64) (retUInt64Slice_0 []uint64, clientErr error) {
	rpcReq := ServiceUInt64SliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt64SliceResponse)
	return rpcResp.RetUInt64Slice_0, nil
}

func (tsc *ServiceGoRPCClient) UInt64Type(v UInt64Type) (retUInt64Type_0 UInt64Type, clientErr error) {
	rpcReq := ServiceUInt64TypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt64TypeResponse)
	return rpcResp.RetUInt64Type_0, nil
}

func (tsc *ServiceGoRPCClient) UInt64TypeMap(v map[UInt64TypeMapKey]UInt64TypeMapValue) (retUInt64TypeMap_0 map[UInt64TypeMapKey]UInt64TypeMapValue, clientErr error) {
	rpcReq := ServiceUInt64TypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt64TypeMapResponse)
	return rpcResp.RetUInt64TypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) UInt64TypeMapTyped(v UInt64TypeMapTyped) (retUInt64TypeMapTyped_0 UInt64TypeMapTyped, clientErr error) {
	rpcReq := ServiceUInt64TypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUInt64TypeMapTypedResponse)
	return rpcResp.RetUInt64TypeMapTyped_0, nil
}

func (tsc *ServiceGoRPCClient) UIntMap(v map[uint]any) (retUIntMap_0 map[uint]any, clientErr error) {
	rpcReq := ServiceUIntMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUIntMapResponse)
	return rpcResp.RetUIntMap_0, nil
}

func (tsc *ServiceGoRPCClient) UIntSlice(v []uint) (retUIntSlice_0 []uint, clientErr error) {
	rpcReq := ServiceUIntSliceRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUIntSliceResponse)
	return rpcResp.RetUIntSlice_0, nil
}

func (tsc *ServiceGoRPCClient) UIntType(v UIntType) (retUIntType_0 UIntType, clientErr error) {
	rpcReq := ServiceUIntTypeRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUIntTypeResponse)
	return rpcResp.RetUIntType_0, nil
}

func (tsc *ServiceGoRPCClient) UIntTypeMap(v map[UIntTypeMapKey]UIntTypeMapValue) (retUIntTypeMap_0 map[UIntTypeMapKey]UIntTypeMapValue, clientErr error) {
	rpcReq := ServiceUIntTypeMapRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUIntTypeMapResponse)
	return rpcResp.RetUIntTypeMap_0, nil
}

func (tsc *ServiceGoRPCClient) UIntTypeMapTyped(v UIntTypeMapTyped) (retUIntTypeMapTyped_0 UIntTypeMapTyped, clientErr error) {
	rpcReq := ServiceUIntTypeMapTypedRequest{V: v}
	rpcRes, rpcErr := tsc.Client.Call(rpcReq)
	if rpcErr != nil {
		clientErr = rpcErr
		return
	}
	rpcResp := rpcRes.(ServiceUIntTypeMapTypedResponse)
	return rpcResp.RetUIntTypeMapTyped_0, nil
}
