/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as github_com_foomo_gotsrpc_v2_tests_union_private from './vo-private'; // ./client/vo-private.ts to ./client/vo-private.ts

// github.com/foomo/gotsrpc/v2/tests/union/private.UnionStringA
export enum UnionStringA {
	One = "one",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/union/private.UnionStringB
export enum UnionStringB {
	Four = "four",
	Three = "three",
}
// github.com/foomo/gotsrpc/v2/tests/union/private.UnionStructAValueA
export enum UnionStructAValueA {
	One = "one",
	Three = "three",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/union/private.UnionStructAValueB
export enum UnionStructAValueB {
	One = "one",
	Three = "three",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/union/private.InlineStruct
export interface InlineStruct extends github_com_foomo_gotsrpc_v2_tests_union_private.InlineStructA, github_com_foomo_gotsrpc_v2_tests_union_private.InlineStructB {
	value:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/private.InlineStructA
export interface InlineStructA {
	valueA:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/private.InlineStructB
export interface InlineStructB {
	valueB:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/private.InlineStructPtr
export interface InlineStructPtr extends Partial<github_com_foomo_gotsrpc_v2_tests_union_private.InlineStructA>, Partial<github_com_foomo_gotsrpc_v2_tests_union_private.InlineStructB> {
	bug?:github_com_foomo_gotsrpc_v2_tests_union_private.InlineStructB;
	value:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/private.UnionStructA
export interface UnionStructA {
	kind:'UnionStructA';
	value:github_com_foomo_gotsrpc_v2_tests_union_private.UnionStructAValueA;
	bar:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/private.UnionStructB
export interface UnionStructB {
	kind:'UnionStructB';
	value:github_com_foomo_gotsrpc_v2_tests_union_private.UnionStructAValueB;
	foo:string;
}
// end of common js