/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as github_com_foomo_gotsrpc_v2_tests_union_server from './vo'; // ./client/vo.ts to ./client/vo.ts

// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStringA
export enum UnionStringA {
	One = "one",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStringB
export enum UnionStringB {
	Four = "four",
	Three = "three",
}
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStructAValueA
export enum UnionStructAValueA {
	One = "one",
	Three = "three",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStructAValueB
export enum UnionStructAValueB {
	One = "one",
	Three = "three",
	Two = "two",
}
// github.com/foomo/gotsrpc/v2/tests/union/server.InlineStruct
export interface InlineStruct extends github_com_foomo_gotsrpc_v2_tests_union_server.InlineStructA , github_com_foomo_gotsrpc_v2_tests_union_server.InlineStructB {
	value:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/server.InlineStructA
export interface InlineStructA {
	valueA:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/server.InlineStructB
export interface InlineStructB {
	valueB:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/server.InlineStructPtr
export interface InlineStructPtr extends Partial<github_com_foomo_gotsrpc_v2_tests_union_server.InlineStructA> , Partial<github_com_foomo_gotsrpc_v2_tests_union_server.InlineStructB> {
	bug?:github_com_foomo_gotsrpc_v2_tests_union_server.InlineStructB;
	value:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionString
export const UnionString = { ...github_com_foomo_gotsrpc_v2_tests_union_server.UnionStringA, ...github_com_foomo_gotsrpc_v2_tests_union_server.UnionStringB }
export type UnionString = github_com_foomo_gotsrpc_v2_tests_union_server.UnionStringA | github_com_foomo_gotsrpc_v2_tests_union_server.UnionStringB
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStruct
export type UnionStruct = github_com_foomo_gotsrpc_v2_tests_union_server.UnionStructA | github_com_foomo_gotsrpc_v2_tests_union_server.UnionStructB | undefined
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStructA
export interface UnionStructA {
	kind:'UnionStructA';
	value:github_com_foomo_gotsrpc_v2_tests_union_server.UnionStructAValueA;
	bar:string;
}
// github.com/foomo/gotsrpc/v2/tests/union/server.UnionStructB
export interface UnionStructB {
	kind:'UnionStructB';
	value:github_com_foomo_gotsrpc_v2_tests_union_server.UnionStructAValueB;
	foo:string;
}
// end of common js