name: Release Tag

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod

      - id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}