name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v4
        with:
          working-directory: ${{ matrix.gomod }}

      - name: Run tests
        run: go test -v ./...

