name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version-file: go.mod

      - uses: actions/setup-node@v5

      - name: Run yarn install
        working-directory: example
        run: yarn install

      - name: Run go mod tidy
        run: |
          make tidy
          git diff --exit-code

      - uses: golangci/golangci-lint-action@v8

      - name: Make examples
        run: |
          make examples
          git diff --exit-code

      - name: Run tests
        run: make test

