name: Test Branch

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v3

      - uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v8
        with:
          install-mode: none

      - uses: actions/setup-node@v5

      - name: Run yarn install
        working-directory: example
        run: yarn install

      - name: Run go mod tidy
        run: make tidy && git diff --exit-code

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Make examples
        run: |
          make examples
          git diff --exit-code


