/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2 - DO NOT EDIT.
import * as time from './vo-time'; // ./client/vo-time.ts to ./client/vo-time.ts

// time.Time
export interface Time {
}
// end of common js