/* eslint:disable */
// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v3 - DO NOT EDIT.

// github.com/foomo/gotsrpc/v3/tests/time/server.TimeStruct
export interface TimeStruct {
	time:number;
	timePtr:number|null;
	timePtrOmit?:number;
}
// end of common js